### ISSUE TITLE
Enable non-programmers to run oTree experiments

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#117]
- create a heroku account
- install the heroku toolbelt
- create a server
- git pull
- git push to heroku
- syncdb
- go to /demo

Git pull, then push to a Heroku server, then syncdb. That's the best way.

This used to be very urgent, but that's before we had the demo feature.

**Comment by leliel12** [comment]
lets rock

**Comment by leliel12** [comment]
i wrote the first version of the install script. The functionallity is really easy and its full multi-platform. The steps of the installer are:

1. On start up determines if the operating system is windows or posix and 
   configure all the global vars.
2. Download the zip of the master branch from oTree github repository.
3. Unpack the zip inside the working directory. 
4. Creates an install script inside working dir.
5. Execute the install script:
    1. Convert the working directory in a virtualenv.
    2. Activate the virtualenv
    3. Install the rquirements inside the virtualenv
    4. Execute *resetdb* of the virtualenv
6. Creates a run script inside the oTree dir.
7. Execute the run script
8. Open the browser on /demo

You can see the whole process here: https://www.youtube.com/watch?v=zlsMG9l4obw&feature=youtu.be (linux) and https://www.youtube.com/watch?v=wKRSbefG_hw&feature=youtu.be (windows)

**Comment by leliel12** [comment]
Now i will refactor the code and pack into exe for windows

**Comment by oTree-org** [comment]
This looks great! I tested on Windows and it works :)

**Comment by leliel12** [comment]
https://github.com/oTree-org/otree-launcher <<< the issue solution is implemented in this repo
