### ISSUE TITLE
API for validation of fields that depend on each other

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#239]
In models.py, you can define validation of a field like this: https://github.com/oTree-org/oTree/wiki/Models#def-field_name_error_messageself-value

However, there currently is no way to validate multiple fields that depend on each other. My suggestion is that there should be a method on the view (probably implemented in otree.views.abstract.FormPageMixin) with the following signature:

    def error_message(self, values):

Where "values" is the cleaned_data dict.

The issue that makes this a little bit complicated is that validation occurs in the form, but the form is not normally able to access a method on the view. Possible solutions:

(a) pass the view instance to the form as a kwarg (would have to figure out how to do this with modelform_factory).
(b) do the validation in the view, rather than the form.

**Comment by leliel12** [comment]
i implement this in a very simple way... inside the model. The error_messages ocurrs at the end of all validations and accept as parameter a cleaned_data dict

**Comment by leliel12** [comment]
For concistency reasons y also move all `FIELD_label` methods
