### ISSUE TITLE
Record all invalid submissions on forms

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#243]
Record all submissions on forms that fail validation.

**Comment by leliel12** [comment]
Im interesting on this issue so i started a discussion about it.

My approach is to use another app to record all the errors. This app can be used to extend the registrations of more events  in the future

**Comment by oTree-org** [comment]
I need to think about this some more...a lot of our validation happens client-side (e.g. using HTML5 max/min), and I have to think about whether we want to record these client-side validation errors.

**Comment by oTree-org** [comment]
Closing so we can focus on higher priority bugs.
