### ISSUE TITLE
Refactor otree.session to be not a separate django-app.

### ISSUE THREAD

**Issue by gregmuellegger** [oTree-org/otree-core#263]
Currently there need to be two different apps in the `INSTALLED_APPS` setting to make otree work: `otree` and `otree.session`.
However these two apps are tightly coupled and cannot be used separately. So the goal should be to have only one app that needs to be registered. This will make handling migrations easier since we only need to maintain one line of migrations.

**Comment by gregmuellegger** [comment]
I started work on this and added migrations that move the models that lived in `otree.session.models` to be now in `otree.models.session` without need to reset the database.

`otree.session` is still in the `INSTALLED_APPS` setting but that is strictly necessary until everyone who has a running otree installation (and doesn't want to reset the db) has applied the latest migrations. Once we are sure everyone is on the same page (for example two releases later), we can remove `otree.session` from `INSTALLED_APPS`.

I documented a few things that can be done once we are in that situation in `otree/migrations/0003_squash_0002_move_session_models_into_otree.py`: https://github.com/oTree-org/otree-core/blob/master/otree/migrations/0003_squash_0002_move_session_models_into_otree.py#L10

**Comment by oTree-org** [comment]
Thank you! We can delete `otree.session` from `INSTALLED_APPS` now.

**Comment by gregmuellegger** [comment]
Ok, I will take care of that later this week.

**Comment by gregmuellegger** [comment]
@oTree-org : Is there a particular reason why you removed the otree migrations in this commit: https://github.com/oTree-org/otree-core/commit/a0a687288cdd913f2a042e6af1de2ea5feb4e7a8 ?

**Comment by oTree-org** [comment]
@gregmuellegger oops no...sometimes when I'm refactoring models, I delete and re-create migrations files from scratch. I guess I forgot to `git add` the newly generated migrations.

**Comment by oTree-org** [comment]
By the way, I know in the future when many people are using oTree in production, we should do migrations in a way that they don't break users' existing oTree instances, but for now I am not concerned about that so I consider it easiest just to delete and re-create. In fact, I am not concerned about compat in general at this point.

**Comment by oTree-org** [comment]
Oh sorry, I realized you wrote a comment in one of the migrations files, didn't realize.

**Comment by gregmuellegger** [comment]
Ok the work for this ticket is complete and in master. So I close it now.
