### ISSUE TITLE
Implement Slider widget

### ISSUE THREAD

**Issue by gregmuellegger** [oTree-org/otree-core#264]
We should have a much requested Slider widget to use with a min-, max-value range. Users should be able to specify a step-size.

The slider should show the currently set value next to it. If no default value is specified, the slider should either start on the very left boundary or in the center of the range.

It might be worth investigating what native support browsers offer for slider widgets.

The widget should be called "slider" and not "range" since this what otree users are asking for.

**Comment by oTree-org** [comment]
Fixed a while ago
