### ISSUE TITLE
Merge "monitor session" admin page with "advance session" page

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#267]
Currently, oTree has these 2 experimenter pages for each session. In the latest master of otree-core, they are both listed on the start links page, e.g. http://127.0.0.1:8000/demo/public_goods/

![image](https://cloud.githubusercontent.com/assets/5423929/5449786/e8672b94-853e-11e4-9deb-8eefc32df146.png)

(1) "Monitor participants". Links to the Participants changelist page in the admin, filtered for Participantns i this session.

(2) "Advance participants". Lets the admin advance the slowest participant in the session.

I think **these 2 pages should be combined**, because it lets experimenters monitor how participants are progressing, and then advance the participants if somebody is too slow. Also, currently, the "monitor participants" page does not provide any feedback/information after the button is clicked, indicating what happened. It would be better if they could click a button and then see in the changelist table which participants were moved forward, to which page.

I think the button that says "Advance slowest participant(s)" could be added right above the changelist table, where there is the blue line in this picture:

![image](https://cloud.githubusercontent.com/assets/5423929/5449682/2b29df5a-853d-11e4-9477-ae529a0fff6a.png)

(I am open to suggestions for better UI/layout. Also, eventually there will be other buttons/commands, like "Skip subsession", or "Assign participants to groups".)

By the way, currently the "monitor participants" page is just the full Participants changelist page, with a filter applied, like [http://127.0.0.1:8000/admin/session/participant/?session=1](http://127.0.0.1:8000/admin/session/participant/?session=1). It is defined in `otree.adminlib.session_monitor_url`. Maybe we should create a custom view/URL like `http://127.0.0.1:8000/admin/session/1/monitor_participants`

**Comment by oTree-org** [comment]
Looks great!

**Comment by leliel12** [comment]
Thanks... It was my first time with this level of customization in the admin
