### ISSUE TITLE
"OperationalError: no such column" error message should also recommend "resetdb"

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#270]
If an oTree app developer adds a column to models.py but forgets to `resetdb`, they will get the error `OperationalError: no such column "foo"`. A newbie who sees this error message might not know what it means or how to fix it. We should improve the error message by saying something like "Try resetting the database."

**Comment by leliel12** [comment]
after various solution the best one was a middleware. 

Every  exception message instance of `django.db.utils.OperationalError` was in the message "*try resetting the database*"

**Comment by leliel12** [comment]
futures improvements can be added on `otree.middlewares` classes
