### ISSUE TITLE
Form validation: separate "bounds" into min_value and max_value

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#271]
Sometimes an app programmer might want to specify only the upper bound or only the lower bound for a field. So, we should consider splitting the "bounds" field kwarg and method into "min_value" and "max_value".

For example:

foo = models.IntegerField(bounds = [4,10])

Would become:

foo = models.IntegerField(min_value=4,max_value=10])

(The method FIELD_bounds() should also be split into 2 separate methods, although as those methods should go on the view, not the model, as described in #239. )

This would follow the naming convention of max_length and max_digits.

We could also call them "min" and "max" but those are the names of built-in Python functions. Or we could call them "lower" and "upper" but that is not as clear, in Sent from my iPhone

Another benefit of doing this is that we can add a "step size" argument later. I think that is clearer than adding step size to "bounds":

bounds=[4,10,2]

**Comment by leliel12** [comment]
also i removed unused test on models with bounds
