### ISSUE TITLE
Make NullBooleanField consistent with other oTree model fields

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#272]
I would like to make oTree's boolean model field work the following way, to be consistent with how other model fields work in oTree:

(1) `None` is the initial/default value for the field when the model is instantiated
(2) However, if the field is included in a form, we don't allow the blank/None choice...
(3) ...unless the programmer specified `blank=True` in the model field definition.

Current status of implementation:

(1) Already works; in fact, I override all oTree fields so that the initial/default value is None unless otherwise specified
(2) My existing implementation is [here](https://github.com/oTree-org/otree-core/blob/c7b13ae38cd2e55ec818bd37d57c51f80459b26d/otree/forms/forms.py#L282). I wrote this a while back, but now I am guessing there might be a smarter/more efficient way to enforce this by implementing it on the model field rather than the form field
(3) This is where I am stuck. I tried writing it like this:

```
                if name in null_boolean_field_names and value is None:
                    model_field = self.instance._meta.get_field_by_name(name)[0]
                    if not getattr(model_field, 'blank', None):
                        msg = _('This field is required.')
                        raise forms.ValidationError(msg)
```

But then if I try setting blank=False in an example game, it seems to have no effect. I guess this is because in the [Django source](https://github.com/django/django/blob/0f54cf28c09a80254571487e3af93be2096cfdac/django/db/models/fields/__init__.py#L2020) `blank=True` is hardcoded?

I also think it is best to simply rename this field "BooleanField" rather than `NullBooleanField` because that's what a typical oTree user would expect.

**Comment by oTree-org** [comment]
Found some old discussion in the second half of this post: https://groups.google.com/d/msg/django-developers/zOv6zsYuFcc/BdZGJKZbZQ0J

**Comment by leliel12** [comment]
well after some investigation about it. I this the "rename" is the best solution. 

Also, your solution is (IMHO) the best, because by default the boolean field can ONLY have 2 values True or False [the NullBooleanField in django is a simple hack for historical reasons. (Probably a best Tri State widgest is a combo box or something like that)] So if the validation will exist in view level (only validate if the user include the field in the form) your implementation is the correct.
