### ISSUE TITLE
Admin: env vars should determine whether login is required

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#273]
When oTree is installed for local development, we should make the whole admin accessible without logging in. This makes development and testing easier, since you don't have to go through the login screen every time you want to create or monitor a session.

However, of course when you are finished local development and need to deploy your site publicly, there should be a way to turn on a mode where passwords are required.

I think a good way to do this is through environment variables. We could have an env variable called `OTREE_AUTH_LEVEL` or `OTREE_ACCESS_MODE`.

- If it is not set, then there are no access restrictions (so, this would be the default when you first set up oTree locally).
- If you set it to EXPERIMENT, then it will behave as if you are running an experiment to participants. All parts of the admin and demo site require login, so that participants can only play if they have a link.
- If you set it to DEMO, then it will behave as if you are putting your apps online for public demo. This means people can access the demo site and play games and see the admin panel for their session, but they cannot do other admin actions, like seeing the admin homepage, editing global settings, etc.

For implementation, I guess we would implement a decorator or mixin that specifies the auth level. Django provides decorators in `django.contrib.auth.decorators` that we could customize:

https://docs.djangoproject.com/en/1.7/_modules/django/contrib/auth/decorators/

Once that is implemented, we would apply these decorators to the individual view classes in `otree.views.admin` and `otree.views.demo`, to restrict them to DEMO or EXPERIMENT (or no restriction).

For example:

Pages that require auth in experiment mode but not in demo mode:
* `oTree.views.demo.{DemoIndex,CreateDemoSession}`
* `oTree.views.admin.Session{Monitor,Results,StartLinks,Payments,EditProperties,Description}`

Pages that require auth in demo mode and experiment mode:
* `oTree.views.admin.{SessionTypesToCreate,CreateSession,AdminHome,MturkInfo,PersistentLabURLs}`

**Comment by gregmuellegger** [comment]
Having no restriction by default might be a little loose policy. A suggestion: If `DEBUG=True`, then no restriction is in place by default. If `DEBUG=False`, then `OTREE_AUTH_LEVEL` defaults to `EXPERIMENT`.

**Comment by oTree-org** [comment]
Good point, I agree.
