### ISSUE TITLE
Launcher virtualenv should be easily accessible from the command line

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#275]
People who install oTree with the [launcher](https://github.com/oTree-org/otree-launcher) will sometimes need to run oTree commands from the command line that are not available through the GUI, such as:

```
./otree startapp
./otree test
./otree shell
```

However, currently, if they try any of these commands, it will give an `ImportError`, because the launcher installs oTree inside a virtualenv in `~/.otree-launcher` or (on Windows) `%AppData%/oTree-launcher`. This virtualenv must be activated before the `otree` script will work.

On Mac/Linux the command is:

`~/.otree-launcher/venv/bin/activate`

On Windows (cmd), it is:

`%APPDATA%/otree-launcher/venv/Scripts/activate`

For windows users on PowerShell the command may be more complicated; I can't figure it out at the moment. Something like:

`powershell -noexit "$env:APPDATA\otree-launcher/venv/Scripts/activate"`

I see a few ways to address this issue:

**(1) add documentation that the user should either explicitly activate this virtualenv before they run the otree script, or add it to their command shell's startup file.**

The problem is that it's cumbersome to type this command manually each time before you run the oTree command. And although Mac/Linux make it easy to add something to `.bash_profile`, it is not straightforward on Windows (requires editing the registry: http://superuser.com/questions/302194/automatically-executing-commands-when-a-command-prompt-is-opened)

**(2) make the launcher install oTree onto the system-wide Python (not virtualenv)**

The main target audience for the installer is a beginner programmer who is installing oTree on their personal computer (not a server) so probably doesn't need multiple virtual environments. So maybe it is reasonable to use the system Python installation.

However, this option would not be desirable for people who have limited permissions on their machine, or developers who need a virtual environment. So, if we go with this option, we should probably provide an option in the GUI to select a different Python interpreter than the system-wide one (by browsing to the Python executable in the virtualenv). We probably also want to give an option to skip the "First run setup". That way, more skilled users could clone the repo themselves and install their own virtualenv, but use the convenient launcher GUI for `runserver`/`resetdb`, etc. this is something I personally would find useful.

**(3) button in the launcher GUI to open the command window**

This would launch the system's terminal/command prompt to the current project dir, and automatically run the venv activate script.

This seems like a fairly nice solution in theory, I just don't know how hard it is and what complications could arise.

**(4) add to the repo an `activate_venv.py` script**

This script could sit in the root of the project and the user could manually run it when they need to activate the virtualenv. They could also edit this file to change the path to the venv. (This idea is not my favorite but I am mentioning it anyways)

Thoughts?

**Comment by oTree-org** [comment]
I investigated option 1 a bit more. For background, Windows has 2 built-in command prompts: the classic CMD shell and the more modern PowerShell.

PowerShell has a "profile" similar to .bash_profile where the user could paste the command to activate the virtualenv. (They would also have to run a one-time command `Set-ExecutionPolicy` to allow the activate script to run.)

So, if we tell Windows users to use PowerShell, it is still somewhat cumbersome, but not as bad as modifying the Windows registry.

Nevertheless, I am curious about the possibility of options 2 or 3 above, because I think the user experience would be better and would not require the manual step and reading docs.

**Comment by leliel12** [comment]
The solution will be the option 3

**Comment by leliel12** [comment]
Another way is add the "activate_this.py" inside the otree runner, but is more easy to simple call the bat and open the console... also this behavior was a bug for me when i writing the launcher

**Comment by leliel12** [comment]
i fixed most of error and also add another features but i stil has an error on windows

> The oTree Launcher says 'Hello'
> Creating virtualenv in 'C:\Users\VBOx\AppData\Roaming\otree-launcher\oTree'...
> Downloading requirements file...
> Creating virtualenv install script...
> Creating venv, please wait (this may take a few minutes)...
> New python executable in C:\Users\VBOx\AppData\Roaming\otree-launcher\oTree\Scripts\python.exe
> Installing setuptools, pip...
> done.
> You are using pip version 6.0.6, however version 6.0.8 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Collecting pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-6.0.8-py2.py3-none-any.whl#md5=41e73fae2c86ba2270ff51c1d86f7e09
>   Downloading pip-6.0.8-py2.py3-none-any.whl (1.3MB)
> Installing collected packages: pip
>   Found existing installation: pip 6.0.6
>     Uninstalling pip-6.0.6:
>       Successfully uninstalled pip-6.0.6
> 
>   Exception:
>   Traceback (most recent call last):
>     File "C:\Users\VBOx\AppData\Roaming\otree-launcher\oTree\lib\site-packages\pip\basecommand.py", line 232, in main
>       status = self.run(options, args)
>     File "C:\Users\VBOx\AppData\Roaming\otree-launcher\oTree\lib\site-packages\pip\commands\install.py", line 347, in run
>       root=options.root_path,
>     File "C:\Users\VBOx\AppData\Roaming\otree-launcher\oTree\lib\site-packages\pip\req\req_set.py", line 560, in install
>       requirement.commit_uninstall()
>     File "C:\Users\VBOx\AppData\Roaming\otree-launcher\oTree\lib\site-packages\pip\req\req_install.py", line 677, in commit_uninstall
> 
>     File "C:\Users\VBOx\AppData\Roaming\otree-launcher\oTree\lib\site-packages\pip\req\req_uninstall.py", line 153, in commit
>       rmtree(self.save_dir)
>     File "C:\Users\VBOx\AppData\Roaming\otree-launcher\oTree\lib\site-packages\pip\utils\__init__.py", line 58, in rmtree
>       @retry(stop_max_delay=3000, wait_fixed=500)
>     File "C:\Python27\Lib\shutil.py", line 247, in rmtree
>       rmtree(fullname, ignore_errors, onerror)
> Initial setup complete.
Click on the 'Deploys' menu to create a new deploy.
>     File "C:\Python27\Lib\shutil.py", line 247, in rmtree
>       rmtree(fullname, ignore_errors, onerror)
>     File "C:\Python27\Lib\shutil.py", line 247, in rmtree
>       rmtree(fullname, ignore_errors, onerror)
>     File "C:\Python27\Lib\shutil.py", line 247, in rmtree
>       rmtree(fullname, ignore_errors, onerror)
>     File "C:\Python27\Lib\shutil.py", line 247, in rmtree
>       rmtree(fullname, ignore_errors, onerror)
>     File "C:\Python27\Lib\shutil.py", line 247, in rmtree
>       rmtree(fullname, ignore_errors, onerror)
>     File "C:\Python27\Lib\shutil.py", line 247, in rmtree
>       rmtree(fullname, ignore_errors, onerror)
>     File "C:\Python27\Lib\shutil.py", line 252, in rmtree
>       onerror(os.remove, fullname, sys.exc_info())
>     File "C:\Users\VBOx\AppData\Roaming\otree-launcher\oTree\lib\site-packages\pip\utils\__init__.py", line 70, in rmtree_errorhandler
>       # convert to read/write
>   WindowsError: [Error 5] Access is denied: 'c:\\users\\vbox\\appdata\\local\\temp\\pip-l7vntm-uninstall\\users\\vbox\\appdata\\roaming\\otree-launcher\\otree\\scripts\\pip.exe'
>

**Comment by oTree-org** [comment]
I also get the same error.

**Comment by leliel12** [comment]
pleae check if it works... the console dont work on macosx (basically beause i dont has an osx. We need to fix this

**Comment by oTree-org** [comment]
OK it works now. I also tested launching the console and that works too

**Comment by leliel12** [comment]
fixed in https://github.com/oTree-org/otree-launcher/commit/d3e03146eafd89f6bdc08bc2e511453eb1036540
