### ISSUE TITLE
FIELD_choices  doesn't work, if elements are nested tuples or lists

### ISSUE THREAD

**Issue by khazamov** [oTree-org/otree-core#277]
here is my modelfield
 

```
decision = models.CharField(    
        doc="""This player's decision""", 
        widget=widgets.RadioSelect()
    )
```

I defined method called decision_choices in views.py; if I make it return `['Cooperate', 'Defect']` it works, but not if I make it return `[ ['C','Cooperate'],['D','Defect'] ]`

The choices get displayed correctly, but when I submit a choice I get 
`Value must be one of: ['C','Cooperate'], ['D', 'Defect']"` 

The error doesn't occur if choices are defined in the models.py of selected game.

**Comment by leliel12** [comment]
Fixed the title: The problem is not if the structure is a tuple  (https://docs.python.org/2/tutorial/datastructures.html#tuples-and-sequences) or a list. The bug is becaus the tested sequences

**Comment by oTree-org** [comment]
I think this is a regression.

**Comment by leliel12** [comment]
after some tests this issue only fails when widget=check_box

**Comment by leliel12** [comment]
the problem is only the validation

**Comment by oTree-org** [comment]
yes, here is an example app with this bug:

https://www.dropbox.com/s/16txn56rtimdy4e/FOO_choices%20fail.zip?dl=0
