### ISSUE TITLE
Launcher should have a button to open project directory

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#280]
It would be nice if the launcher had a button that would open The otree project directory in Windows Explorer or Mac Finder, so that a user could easily access their python source files and edit them.

**Comment by leliel12** [comment]
i really hate this jajaja... im gonna simplyfy some thins in console and
this can be implemented easily

2015-03-05 11:23 GMT-03:00 oTree-org <notifications@github.com>:

> It would be nice if the launcher had a button that would open The otree
> project directory in Windows Explorer or Mac Finder, so that a user could
> easily access their python source files and edit them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/280>.
>



-- 
Juan B Cabral

**Comment by leliel12** [comment]
fixed in https://github.com/oTree-org/otree-launcher/commit/54963aad681249347a4ced2459468794d118b1d1
