### ISSUE TITLE
Mechanical Turk: before publishing, check if server is accessible from Internet

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#283]
People might make the mistake of thinking they can publish their session to Amazon mechanical Turk when they are just running oTree on localhost. Of course, they first need to deploy oTree to a publicly accessible Web server.

So, before we allow the user to publish the session, we should check that the server is accessible from the Internet. Maybe there is an existing Web service to which you can pass a URL, and it will ping that URL and return the result. Or, a more basic check would be to simply assert that the URL is not "localhost"

**Comment by oTree-org** [comment]
Maybe can use this: https://isitup.org/api/api.html

**Comment by leliel12** [comment]
this code is already working in the launcher im going to adatp and use without any dependencies

**Comment by leliel12** [comment]
i already write a function to "auto ping" the deploy of otree. Now the question its simple: where is my deployment URL? we use the sites app? or in other case if it only configures in mturk probably we can add one settings more like "PUBLIC_URL"

**Comment by oTree-org** [comment]
We would check it in otree.views.mturk.SessionCreateHit. There is a checkbox in this page's form where the user can specify to use the mechanical Turk sandbox (if unchecked, uses the mechanical Turk live site). If they are using the live site, then the server must be accessible from the Internet. So if the server is not accessible from the Internet, we should unselect and disable this checkbox.

To get the URL of the current server, maybe we can use self.request.build_absolute_uri in the view. Then we can know if we are currently on localhost, etc.

**Comment by oTree-org** [comment]
And if the checkbox is a disabled, we would display a message explaining that they first need to put their site on the Internet.

**Comment by leliel12** [comment]
but the localhost its only an alias its posible that some OS don't has
"localhost" defined. Also in linux you can access localhost using your own
hostname

2015-03-14 22:01 GMT-03:00 oTree-org <notifications@github.com>:

> We would check it in otree.views.mturk.SessionCreateHit. There is a
> checkbox in this page's form where the user can specify to use the
> mechanical Turk sandbox (if unchecked, uses the mechanical Turk live site).
> If they are using the live site, then the server must be accessible from
> the Internet. So if the server is not accessible from the Internet, we
> should unselect and disable this checkbox.
>
> To get the URL of the current server, maybe we can use
> self.request.build_absolute_uri in the view. Then we can know if we are
> currently on localhost, etc.
>
> > On Mar 15, 2015, at 8:51 AM, Juan BC <notifications@github.com> wrote:
> >
> > i already write a function to "auto ping" the deploy of otree. Now the
> question its simple: where is my deployment URL? we use the sites app? or
> in other case if it only configures in mturk probably we can add one
> settings more like "PUBLIC_URL"
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/283#issuecomment-80786095>
> .
>



-- 
Juan B Cabral

**Comment by oTree-org** [comment]
Yes that's true. So we should use a more general technique to test if the current server is accessible from the Internet. I think a simple solution is best, even if it doesn't catch 100% of the cases. What technique are you thinking to use?

**Comment by leliel12** [comment]
probably this stackoverflow question can explain the problem that i see http://stackoverflow.com/questions/4093999/how-to-use-django-to-get-the-name-for-the-host-server

**Comment by oTree-org** [comment]
We can get the host name from the current request. because we need to do this ping check when the user loads the "mturk" tab of their session page, otree.views.mturk.SessionCreateHit. So I think we can use self.request inside the "get" method of that class to access the server name. I don't think we need a global settings variable for this. What do you think?

**Comment by leliel12** [comment]
ok no problem

2015-03-17 13:30 GMT-03:00 oTree-org <notifications@github.com>:

> We can get the host name from the current request. because we need to do
> this ping check when the user loads the "mturk" tab of their session page,
> otree.views.mturk.SessionCreateHit. So I think we can use self.request
> inside the "get" method of that class to access the server name. I don't
> think we need a global settings variable for this. What do you think?
>
> Sent from my phone
>
> > On Mar 18, 2015, at 12:11 AM, Juan BC <notifications@github.com> wrote:
> >
> > probably this stackoverflow question can explain the problem that i see
> http://stackoverflow.com/questions/4093999/how-to-use-django-to-get-the-name-for-the-host-server
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/283#issuecomment-82451107>
> .
>



-- 
Juan B Cabral

**Comment by leliel12** [comment]
A 500 error was a correct response when this fails http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error

**Comment by leliel12** [comment]
nice package to use https://pypi.python.org/pypi/IPy/
