### ISSUE TITLE
Launcher: ImportError: cannot import name hackbrowser

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#285]
On Windows, I click otree.bat and right away get this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "otree_launcher\gui.py", line 35, in <module>
    from .libs import splash, hackbrowser
ImportError: cannot import name hackbrowser
Press any key to continue . . .
```

This import is unused and there is no other mention of `hackbrowser` anywhere in the code base.

**Comment by leliel12** [comment]
fix on https://github.com/oTree-org/otree-launcher/commit/6520b3082987117874b562b2e14e6e62cc2fbbac
