### ISSUE TITLE
Launcher: on Windows, file manager doesnt open to right directory

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#287]
When I click the file manager button, it opens to my "Documents" directory rather then the oTree project location. I think this happens because in core.open_filemanager, wrkpath contains "/" characters, but when I tested from the command prompt, "start explorer" only opens the correct directory if the path contains backslashes.

**Comment by leliel12** [comment]
fix in https://github.com/oTree-org/otree-launcher/commit/f5573143ab4ffdd8a38d4ac69e2515260e482ba3
