### ISSUE TITLE
Launcher: buttons in GUI should have tooltips

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#288]
The buttons in the launcher, especially "open filemanager", "open command prompt", and "change directory" should have text labels that are displayed when you hover with the mouse, so that people know what happens when they click them.

**Comment by leliel12** [comment]
fix https://github.com/oTree-org/otree-launcher/commit/732d051fa18e9b5c5fe18948a619d9380f2deb1a

Please check the typos
