### ISSUE TITLE
Require session_type names to be unique

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#292]
We should add a check in otree/checks that ensures that each session_type in settings.py has a unique name. Also maybe the display_name should be unique as well.

**Comment by leliel12** [comment]
i don't thing is usefull to ensure that display name is unique. mostly
because in all the frameworks out there the display name is used for create
duplicated name

2015-03-17 1:16 GMT-03:00 oTree-org <notifications@github.com>:

> We should add a check in otree/checks that ensures that each session_type
> in settings.py has a unique name. Also maybe the display_name should be
> unique as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/292>.
>



-- 
Juan B Cabral

**Comment by oTree-org** [comment]
Ok sounds good.

**Comment by leliel12** [comment]
otree its broken because the current fix!

**Comment by leliel12** [comment]
The changes was removed now otree work again
