### ISSUE TITLE
Launcher: os.path.expanduser and UnicodeDecodeError

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#295]
See screenshot:

![](https://www.odesk.com/att/~~7H7ONRUz0DUOhi*LfgG1npbjRSfB3vIb)

Seems to be this issue:

http://stackoverflow.com/questions/23888120/an-alternative-to-os-path-expanduser

**Comment by leliel12** [comment]
This bug is generated by this issue with "wont-fix" status:
http://bugs.python.org/issue13207
this is the only solution is this
http://stackoverflow.com/questions/23888120/an-alternative-to-os-path-expanduser



2015-03-29 0:49 GMT-03:00 oTree-org <notifications@github.com>:

> Assigned #295 <https://github.com/oTree-org/otree-core/issues/295> to
> @leliel12 <https://github.com/leliel12>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/295#event-267789685>.
>



-- 
Juan B Cabral

**Comment by leliel12** [comment]
I fixed the bug in the commit https://github.com/oTree-org/otree-launcher/commit/03c92badf67f37f7fdc1a07b7446b0133245b115

Please test and inform the results. The bad thing about this issue is we can't do anything more becaus is a bug of py2 itself. The solution is to move all the oTree infrastructure to py3 or use something like [six](https://pythonhosted.org/six/)

**Comment by oTree-org** [comment]
A user reports this issue is still occurring:

![screenshot-2015-04-14_23 50 47](https://cloud.githubusercontent.com/assets/5423929/7150799/dbe2e01e-e35a-11e4-9c33-5bad90b230c4.png)

**Comment by oTree-org** [comment]
I added Chinese characters to my install path:

`C:\Users\Christopher\Downloads\otree-launcher-master-3\otree-launcher-master-你好`

I got this error (does not occur if I remove the Chinese characters):

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "otree_launcher\gui.py", line 34, in <module>
    from . import cons, core, res
  File "otree_launcher\cons.py", line 67, in <module>
    with open(res.get("version.json")) as fp:
  File "otree_launcher\res\__init__.py", line 41, in get
    raise IOError("Resource '{}' not exists".format(fpath))
IOError: Resource 'version.json' not exists
Press any key to continue . . .
```

If I put the character `é` in my path:

`C:\Users\Christopher\Downloads\otree-launcher-master-3\otree-launcher-master-é`

I get this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "otree_launcher\gui.py", line 34, in <module>
    from . import cons, core, res
  File "otree_launcher\cons.py", line 67, in <module>
    with open(res.get("version.json")) as fp:
  File "otree_launcher\res\__init__.py", line 38, in get
    path = os.path.join(PATH, fpath)
  File "C:\Python27\lib\ntpath.py", line 108, in join
    path += "\\" + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 77: ordinal
 not in range(128)
Press any key to continue . . .
```

**Comment by leliel12** [comment]
i know how to fix this... grrr windows

2015-04-14 22:51 GMT-03:00 oTree-org <notifications@github.com>:

> I added Chinese characters to my install path:
>
>
> C:\Users\Christopher\Downloads\otree-launcher-master-3\otree-launcher-master-你好
>
> I got this error (does not occur if I remove the Chinese characters):
>
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "otree_launcher\gui.py", line 34, in <module>
>     from . import cons, core, res
>   File "otree_launcher\cons.py", line 67, in <module>
>     with open(res.get("version.json")) as fp:
>   File "otree_launcher\res\__init__.py", line 41, in get
>     raise IOError("Resource '{}' not exists".format(fpath))
> IOError: Resource 'version.json' not exists
> Press any key to continue . . .
>
> If I put the character é in my path:
>
>
> C:\Users\Christopher\Downloads\otree-launcher-master-3\otree-launcher-master-é
>
> I get this error:
>
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "otree_launcher\gui.py", line 34, in <module>
>     from . import cons, core, res
>   File "otree_launcher\cons.py", line 67, in <module>
>     with open(res.get("version.json")) as fp:
>   File "otree_launcher\res\__init__.py", line 38, in get
>     path = os.path.join(PATH, fpath)
>   File "C:\Python27\lib\ntpath.py", line 108, in join
>     path += "\\" + b
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 77: ordinal
>  not in range(128)
> Press any key to continue . . .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/295#issuecomment-93144237>
> .
>



-- 
Juan B Cabral

**Comment by leliel12** [comment]
@oTree-org  can you check the improvement for workarround of this bug on dev branch?

**Comment by oTree-org** [comment]
Maybe as a temporary fix we can check if the path contains forbidden characters?

**Comment by leliel12** [comment]
i theory the warning exists. but its hard to deal with this windows particularities

**Comment by leliel12** [comment]
Well after a lot of work arround that doesn't work. Now if you try to run the launcher from a unicde path a error will showed.

This things fails at really low level
