### ISSUE TITLE
Migrate to Django 1.8

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#298]
If our dependencies support 1.8, we can migrate. 

Here are the 1.8 release notes; I will have a look:

https://docs.djangoproject.com/en/1.8/releases/1.8/

**Comment by oTree-org** [comment]
I just reviewed the list. Here are the issues I found:

- Model._meta: should review if any of our usages break. For example, we use `get_field_by_name`
- Forms: maybe some of these affect us, not sure
- `urlpatterns` and other aspects of our urls.py should be reviewed

It is possible that I missed some, especially in parts of the code that I didn't write.

**Comment by leliel12** [comment]
blocked by #362
