### ISSUE TITLE
Launcher on Mac: "CFURLCopyResourcePropertyForKey failed because it was passed this URL which has no scheme:"

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#299]
2 Mac users have reported this error:

```
CFURLCopyResourcePropertyForKey failed because it was passed this URL which has no scheme:
```

This error occurs on the latest version of the launcher. Both users confirmed there are no spaces in the path to the .sh file. Example path:

```
/Users/asanduko/Downloads/otree-launcher-master
```

Email from one user:

> I’m running OS X Yosemite and have version 2.7 of Python installed. I when searching for the error on google, I found that the version of git in the latest version of Xcode is problematic for some reason and it was recommended that I upgrade to git version 2.2.1, which I did, yet I still got the same error.

> Have you ever encountered this error on a Mac? My collaborator uses a linux machine and he has no problem running otree, but he and I couldn’t seem to troubleshoot this on my machine.

**Comment by leliel12** [comment]
I going to ,heck if a new version of dulwich is available. Also i will
implement a checker if git is already available on the system  this will be
used by default

Juan BC (sent from my phone)

**Comment by leliel12** [comment]
![screenshot - 070415 - 23 11 47](https://cloud.githubusercontent.com/assets/299010/7037596/9ba2da7a-dd7b-11e4-9c7c-638a97f8e05e.png)

This is the error? if its true. this dont afect the behavior of otree-launcher. Its some logs from something inside python an (i think) tk widgets

**Comment by leliel12** [comment]
as i say this is not a bug inside otree-launcher http://dolinked.com/questions/33372/cfurlcopyresourcepropertyforkey-failed-because-it-was-passed-this-url-which-has but  in other hand i made the improvements listed above

**Comment by oTree-org** [comment]
@leliel12 I think you are correct. The user reinstalled the launcher and now it is working, despite this error showing up in the console. The user says:

> FYI, even though the launcher is working and I can create a new deploy, etc, I'm still getting the same error in the Terminal. It's not affecting the performance of anything, but just seems strange.
