### ISSUE TITLE
Custom front-end widgets

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#301]
Currently, all oTree games in the library consist of pages with a form consisting of:

* standard form widgets (text input, dropdowns, radio buttons, etc) 
* a "next" button to advance to the next page.

Many users will want to build custom front-end interaction. Examples:

* in the ultimatum game, player 2 just sees 2 buttons: "accept" and "reject", instead of a drop down and a separate "next" button
* in the prisoner's dilemma, the player can click directly on a row of the payoff matrix to make his choice in context.
* in an auction, a player can move a slider to decide how much money to bid, and see a live visualization of how this would affect their profit
* [one oTree user is currently trying to build this] a UI where you have a budget of $1000 and you have to decide how to spend it on  N different resources, each of which has a different unit cost. (interaction between multiple fields)

In principle oTree can work with any JS front-end (jQuery, React, Polymer) as long as the values get stored in correctly named hidden input fields. However, we need further investigation because:

* we need working examples as proof that this works as expected
* we should understand ourselves which JavaScript front ends work best for which task, and how hard it is to implement
* oTree users need examples in the library that they can copy/modify to create their own custom widgets

Additionally, we should consider whether we can build something into oTree that makes it easier for inexperienced programmers to build custom widgets, at least for common use cases.

**Comment by gregmuellegger** [comment]
I experimented with the first three suggestions in your list. They now look like this:

Yes/No buttons:
![image](https://cloud.githubusercontent.com/assets/88278/7351108/8037149e-ed03-11e4-9b9f-d6f9e65b78e7.png)

Custom widgets that doesn't require any extra CSS or JS. Only some boilerplate HTML with Bootstrap CSS classes to make the styling look familiar.

Payoff matrix with buttons:
![image](https://cloud.githubusercontent.com/assets/88278/7351133/ab811208-ed03-11e4-9c1b-d7a64e03d24d.png)

Again no JS neede, however the rows get highlighted when you hover over them. That's implemented with a little custom CSS that is inlined in the template.

Bid in the auction:
![image](https://cloud.githubusercontent.com/assets/88278/7351019/004fbc22-ed03-11e4-8dc3-e572b8dee91f.png)
That includes custom JS, custom CSS and an external library that needs to be shipped with the app. The jQuery UI library comes with the game in the `static/vickrey_auction/` directory.

I wasn't sure on how to visualize the payoff as it depends on the second highest bid in the auction which is ofcourse unkown to the bidder. Do you have any ideas on this?

The changes are in the branch `feature/custom-widgets`:
https://github.com/oTree-org/oTree/tree/feature/custom-widgets
https://github.com/oTree-org/otree-core/tree/feature/custom-widgets


Based on those three examples it is really a good advice for novice programmers and those experimenting with custom widgets, to first look at the generated HTML from the `{% formfield %}` tag,. You can easily copy and paste the markup it into the template and use that as a starting point for modifications. I would include that as a recommendation for beginners in the docs.

I will give the docs later this week a shot and extend them using that advice.

**Comment by oTree-org** [comment]
OK, looks good! I will merge to master.
