### ISSUE TITLE
Migrate Tutorial to Sphinx and Read The docs

### ISSUE THREAD

**Issue by leliel12** [oTree-org/otree-core#305]
I thinks this will be more easy to maintain and integrate the internal documentation of otree and the manual.

I'ts not hard to migrate from markdown to restructured text

**Comment by leliel12** [comment]
@oTree-org what do you think?

**Comment by oTree-org** [comment]
Sure, we can go ahead and do this.

**Comment by oTree-org** [comment]
By the way, I just created a tutorial:
https://github.com/oTree-org/oTree/blob/master/_docs/tutorial.md

**Comment by leliel12** [comment]
Fixed on https://github.com/oTree-org/oTree/commit/bee2c4218524134145f7fb0ac1568af3136b700b
