### ISSUE TITLE
Launcher: "OSError...setuptools pip failed with error code 1"

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#307]
From a user:

![image](https://cloud.githubusercontent.com/assets/5423929/7163148/6ed694f6-e3d3-11e4-9468-7278afb257f6.png)

Details:

* Win 7 machine
* Python 2.7.8, 'PATH' thing works
* tried both bat and exe
* tried to "Run as administrator"
* rebooted system

**Comment by leliel12** [comment]
Can ask the user for open send us the file c:\Users\<USERNAME>\APPDATA\Roaming\otree-launcher\launcher.log?

**Comment by leliel12** [comment]
any news about this?

**Comment by oTree-org** [comment]
The user who reported this error has been on vacation. He told me he will send me the error log this week.

**Comment by oTree-org** [comment]
Here is the error log:

```
New python executable in C:\Users\ROLAND~1\AppData\Roaming\OTREE-~1\oTree\Scripts\python.exe
Installing setuptools, pip...
  Complete output from command C:\Users\ROLAND~1\Ap...e\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\otree\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.8-py2.py3-none-any.whl\pip\__init__.py", line 13, in <module>
  File "C:\otree\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.8-py2.py3-none-any.whl\pip\utils\__init__.py", line 17, in <module>
  File "C:\otree\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.8-py2.py3-none-any.whl\pip\compat\__init__.py", line 14, in <module>
  File "C:\otree\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.8-py2.py3-none-any.whl\pip\compat\dictconfig.py", line 22, in <module>
  File "C:\Python27\Lib\logging\handlers.py", line 26, in <module>
    import errno, logging, socket, os, cPickle, struct, time, re
  File "C:\Python27\Lib\socket.py", line 47, in <module>
    import _socket
ImportError: DLL load failed: The specified procedure could not be found.
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "otree_launcher\libs\virtualenv\virtualenv.py", line 2352, in <module>
    main()
  File "otree_launcher\libs\virtualenv\virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "otree_launcher\libs\virtualenv\virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "otree_launcher\libs\virtualenv\virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "otree_launcher\libs\virtualenv\virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\ROLAND~1\Ap...e\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
```

**Comment by leliel12** [comment]
mmm strange give a couple of hours

2015-04-24 23:22 GMT-03:00 oTree-org <notifications@github.com>:

> Here is the error log:
>
> New python executable in C:\Users\ROLAND~1\AppData\Roaming\OTREE-~1\oTree\Scripts\python.exe
> Installing setuptools, pip...
>   Complete output from command C:\Users\ROLAND~1\Ap...e\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
>   Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\otree\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.8-py2.py3-none-any.whl\pip\__init__.py", line 13, in <module>
>   File "C:\otree\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.8-py2.py3-none-any.whl\pip\utils\__init__.py", line 17, in <module>
>   File "C:\otree\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.8-py2.py3-none-any.whl\pip\compat\__init__.py", line 14, in <module>
>   File "C:\otree\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.8-py2.py3-none-any.whl\pip\compat\dictconfig.py", line 22, in <module>
>   File "C:\Python27\Lib\logging\handlers.py", line 26, in <module>
>     import errno, logging, socket, os, cPickle, struct, time, re
>   File "C:\Python27\Lib\socket.py", line 47, in <module>
>     import _socket
> ImportError: DLL load failed: The specified procedure could not be found.
> ----------------------------------------
> ...Installing setuptools, pip...done.
> Traceback (most recent call last):
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 2352, in <module>
>     main()
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 825, in main
>     symlink=options.symlink)
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 993, in create_environment
>     install_wheel(to_install, py_executable, search_dirs)
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 961, in install_wheel
>     'PIP_NO_INDEX': '1'
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 903, in call_subprocess
>     % (cmd_desc, proc.returncode))
> OSError: Command C:\Users\ROLAND~1\Ap...e\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/307#issuecomment-96121871>
> .
>



-- 
Juan B Cabral

**Comment by leliel12** [comment]
First i can't reproduce the error. And is NOT a oTree-Launcher bug (AFAIK)

Reading two or three forums this error hapend when you have installed multiple versions of python in your windows machine (or multiple installations of the same version). Probably if you previously installed python, anaconda, canopy, web2py, wingware, etc. Most of this software comes with a bundled version of python.

I found this test:

--- FROM http://goo.gl/3N3zJP ---
```python
Please show us the output of:

import sys
print sys.version

import platform
print platform.platform()

import imp
print imp.find_module("_socket")
```
imp.find_module() may either return "_socket" as first argument if the
_socket module is builtin or return the full path to a file. When it's a
full path please install http://www.dependencywalker.com/ and examine
the _socket.pyd file with the tool. It will show you the missing DLLs.

Christian

--- END CITATION ---

**Comment by oTree-org** [comment]
```
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.version
2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
>>> import platform
>>> print platform.platform()
Windows-7-6.1.7601-SP1
>>> import imp
>>> print imp.find_module("_socket")
(<open file 'C:\\Python27\\DLLs\\_socket.pyd', mode 'rb' at 0x0219BCD8>, 'C:\\Python27\\DLLs\\_socket.pyd', ('.pyd', 'rb', 3))
```

**Comment by leliel12** [comment]
With this info now you can analize the _socket.pyd file for the missing dll.
