### ISSUE TITLE
"formfield_is_missing": unnecessary warning if page has a custom widget

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#308]
(@gregmuellegger can you comment on this?)

To ensure that programmers do not forget to include form fields in their template, we have already implemented the "formfield_is_missing" feature that checks that each form field has a corresponding `{% formfield %}` in the template.

The problem is that sometimes people will not use the {% formfield %} tag because they want to write their own widget from scratch. In this case, the warning currently shows up unnecessarily.

The two solutions I see are:

1. make this feature detect when custom widgets are used (I am not sure of the feasibility of this)
2. make the warning less obtrusive. At least we should hide it if `DEBUG` is False. And we could change the wording so that it explains that you can ignore the warning if you are using your own custom widgets.

Either way, I think this warning message can be visually grouped together with the debug info panel at the bottom of the page, because it can also be considered debug info.

By the way, here is an email I got from a user today about this:

> I followed the instructions at https://github.com/oTree-org/oTree/blob/master/README.md#custom-widgets-and-hidden-fields. Unluckily oTree still tells me that I did not include the required form fields in my html template. When I replace the hidden input fields with oTrees formfield-tag, the error message disappears, therefore I guess my data models are setup correctly.

> As I just can't figure out why my code won't work, could you tell me if I am missing something or if I made any mistakes? Or could you give an example on how to use hidden inputs correctly?

**Comment by gregmuellegger** [comment]
Yes, making it less obstrusive is a good idea.

We already discussed in length how it's relatively difficult to make the message 100% reliable in Django. But there is the opportunity to add a few lines of Javascript that reads the error message, and double-checks if the mentioned fields really are not part of the page. The Javascript has more possibilities to more reliably determine that. If it finds all required fields, it hides the message altogether.

I estimate about ~1h for putting the error message in the DEBUG parts of the page and the addition of the Javascript. Shall I give it a try?

**Comment by oTree-org** [comment]
Yes, sounds good, thanks.

**Comment by gregmuellegger** [comment]
That's ready for testing. I moved all of the markup into the debug info block which pushes it down in the page. Also some JS is used to identify wrongly recognized warnings.

**Comment by oTree-org** [comment]
Works for me, thank you!

**Comment by oTree-org** [comment]
Doesn't work in IE11

**Comment by gregmuellegger** [comment]
Ok, sorry for that. Should be fixed now.
