### ISSUE TITLE
{{ player.foo }} should fail if "foo" doesn't exist

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#310]
In a template, `{{ player.foo }}` fails silently if `player` doesn't have a `foo` attribute. Instead, we should throw an exception if a user tries to reference any nonexistent attributes on `player`, `group`, `subsession`, or `Constants`.

(Previously I had the idea to throw an exception for *any* missing variable in templates (i.e. referencing an undeclared variable `{{ foo }}`), but it seems various libraries depend on this behavior. So, I think this more restricted approach would work better.

**Comment by oTree-org** [comment]
Here is where these variables get passed to the template: https://github.com/oTree-org/otree-core/blob/67b60a6740a1262d9862f47ae1be51d313ead95f/otree/views/abstract.py#L654

**Comment by gregmuellegger** [comment]
I don't think that there is a good sane way to make that happen in Django's template language.
Maybe https://docs.djangoproject.com/en/dev/ref/settings/#template-string-if-invalid is a good option. That would make the string that was not defined visible to the user. However this also might break many third-party apps.

**Comment by oTree-org** [comment]
Yes, I tried using `TEMPLATE_STRING_IF_INVALID` but found that it broke 3rd party apps. Closing so we can focus on other bugs.
