### ISSUE TITLE
Launcher closes if user declines update

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#312]
When I opened the launcher I got this message:

![image](https://cloud.githubusercontent.com/assets/5423929/7432761/ef605a82-f065-11e4-8715-fed5b849f9b5.png)

If I click "Cancel", the whole launcher app quits, so I cannot use oTree unless I download the update. Is this intentional? Seems like we should allow people to proceed unless the update is absolutely necessary.

**Comment by oTree-org** [comment]
Also, the word "obsolete" seems too strong. As a user I would interpret this to mean that the current version will no longer work, which is not true.

**Comment by leliel12** [comment]
Exists two messages of update, one is

```
"A new version of oTree-Launcher is available (<VER>)\n"
"Do you want to download it?"
```

This one allow you to download the new version and continue using the old one

But sometimes the changes impact so hard in the core that i need to force the users to use the newest version and the message id

```
"Your version of oTree-Launcher (<VER>) is obsolete\n"
"Do you want to download new {} version?"
```

In this case (as you show in the screenshoot i prevent to use the old versions of otree-launcher. In this case (for example) a lot of unicode errors was fixed or prevented.

The definition of this rule is stored here [otree_launcher/res/version.json](https://github.com/oTree-org/otree-launcher/blob/master/otree_launcher/res/version.json)

The `mandatory` key is the rule from what version is forbiden. Otree launcher read this rules directly from github master branch

**Comment by oTree-org** [comment]
OK, I see, thanks for explaining.
