### ISSUE TITLE
Launcher should create a desktop shortcut

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#313]
Just an idea: what if the launcher created a shortcut on the user's desktop for easy access? So that they don't have to navigate to the subfolder containing the .bat.

http://stackoverflow.com/a/571573/38146

If the user doesn't want the desktop shortcut they could delete it or move it.

Users can easily do this themselves (right click on the .bat, "Create shortcut"). But maybe many users would not think/know they can do this.

The same applies to Mac/Linux.

**Comment by leliel12** [comment]
This is work for an installer. This kind of operation is called post installation hooks

**Comment by oTree-org** [comment]
Closing so we can focus on higher priority bugs.
