### ISSUE TITLE
RemovedInDjango18Warning: `get_query_set` method  should be renamed `get_queryset`

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#320]
After I added the `django-idmap` package to oTree, this warning has been occurring every time I run a `manage.py` command like `resetdb` or `runserver`; would be nice if we could get rid of it:

```
C:\oTree\venv\lib\site-packages\idmap\manager.py:6: RemovedInDjango18Warning: `SharedMemoryManager.get_query_set` method
 should be renamed `get_queryset`.
  class SharedMemoryManager(Manager):
```

Maybe the fix should be done in the `django-idmap` repo? It's hosted here: https://bitbucket.org/tkhyn/django-idmap

**Comment by leliel12** [comment]
https://bitbucket.org/tkhyn/django-idmap/src/f89ac2776132/idmap/manager.py?at=default <<< already fixed
