### ISSUE TITLE
Bots fail for new game "matching_pennies_tutorial"

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#321]
Pull the latest otree-library and otree-core and run:

```
otree test matching_pennies_tutorial -v 3
```

Here is the output I get:

```
...
[INFO|2015-05-25 00:43:12,881] otree.test.runner > 'GET' over first page of all 'matching_pennies_tutorial' participants

[INFO|2015-05-25 00:43:13,793] otree.test.runner > Running subsessions of 'matching_pennies_tutorial'
[INFO|2015-05-25 00:43:13,796] otree.test.runner > Starting subsession 'matching_pennies_tutorial'
[INFO|2015-05-25 00:43:13,796] otree.test.runner > Found test 'matching_pennies_tutorial.tests'
[INFO|2015-05-25 00:43:13,796] otree.test.runner > Creating and staring bots for 'matching_pennies_tutorial'
[INFO|2015-05-25 00:43:14,365] otree.test.client > /p/bolohati/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Tail
s'}
[INFO|2015-05-25 00:43:14,407] otree.test.client > /p/rorizeni/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Tail
s'}
[INFO|2015-05-25 00:43:14,446] otree.test.client > /p/mezapusa/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Tail
s'}
[INFO|2015-05-25 00:43:14,486] otree.test.client > /p/rojisala/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Head
s'}
[INFO|2015-05-25 00:43:14,525] otree.test.client > /p/jurehuzi/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Tail
s'}
[INFO|2015-05-25 00:43:14,566] otree.test.client > /p/hiferugi/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Tail
s'}
[INFO|2015-05-25 00:43:14,678] otree.test.client > /p/tiselefo/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Tail
s'}
[INFO|2015-05-25 00:43:14,786] otree.test.client > /p/feluhuhu/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Head
s'}
[INFO|2015-05-25 00:43:14,851] otree.test.client > /p/runakobu/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Tail
s'}
[INFO|2015-05-25 00:43:14,956] otree.test.client > /p/kehepuvi/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Tail
s'}
[INFO|2015-05-25 00:43:15,043] otree.test.client > /p/hejefulo/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Head
s'}
[INFO|2015-05-25 00:43:15,135] otree.test.client > /p/rapipuri/matching_pennies_tutorial/Choice/1/, {'penny_side': 'Head
s'}
[INFO|2015-05-25 00:43:15,224] otree.test.runner > Stopping bots for 'matching_pennies_tutorial'
FAIL
[INFO|2015-05-25 00:43:15,236] otree > Creating default superuser. Username: admin

======================================================================
FAIL: ExperimentTest For 'matching_pennies_tutorial'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\otree\core\otree\test\runner.py", line 242, in runTest
    self._run_subsession(subsession)
  File "c:\otree\core\otree\test\runner.py", line 209, in _run_subsession
    bot.stop()
  File "c:\otree\core\otree\test\client.py", line 277, in stop
    raise AssertionError(msg)
AssertionError: App matching_pennies_tutorial: Participant 'rojisala' reached the page 1 of 3 at the end of run. Check i
n tests.py if the bot completes the game

----------------------------------------------------------------------
Ran 1 test in 2.848s

FAILED (failures=1)
```

The problem doesn't occur if I change `num_rounds` to 1, so it seems to be caused by rounds. But there are other games that have multiple rounds (like the regular matching pennies) so not sure why the problem only occurs here.

**Comment by leliel12** [comment]
hi i was workong this he las days and i found the bug

The bot say this

```python
class PlayerBot(Bot):

    def play_round(self):

        self.submit(
            views.Choice,
            {"penny_side": random.choice(['Heads', 'Tails'])}
        )

        # submitted in last round
        if self.subsession.round_number == Constants.num_rounds:
            self.submit(views.ResultsSummary)

    def validate_play(self):
        pass
```

The line that says `if self.subsession.round_number == Constants.num_rounds:` always resolve as `False` (except if only have *1 round*, `because round_number` is always `1`). Reading some of the history in some point the concepts of rounds as added and the test framework was never updated. If we made some change in the workflow of the project we need to reevaluate the test framework architecture. 

Feel free to reasign this issue to me if you want

**Comment by oTree-org** [comment]
Ah! yes, that makes sense, thanks. Reassigning.

**Comment by leliel12** [comment]
The approximate line to be changed is the *159* of `otree/test/runner.py`

**Comment by leliel12** [comment]
@oTree-org (change your name at chris :D) in the line *232* of `otree/test/runner.py` we have the next code

```python

        for subsession in sssn.get_subsessions():
            self._run_subsession(subsession)
```

The idea of this is iterates over al the subsesions (but we never iterates over the rounds). I don't know if i have the correct idea but probably by add a nested forloop with the number round of every subsession i gonna be in the correct way of the solution. I this correct?

**Comment by oTree-org** [comment]
The current implementation is correct because rounds are just multiple subsessions within an app.

**Comment by leliel12** [comment]
where is the code in the core that do that?

**Comment by oTree-org** [comment]
https://github.com/oTree-org/otree-core/blob/master/otree/session.py#L175

**Comment by leliel12** [comment]
After a lot of failed strategis the solution will be really simple. The
problem is not the runner itself, the problem is in the round aproach we
can't  guarantee  all the pages will be used in all subsession (the
subsessions are copies because os rounds) only in the last one

El jue, jun 11, 2015 22:51, oTree-org <notifications@github.com> escribió:

> https://github.com/oTree-org/otree-core/blob/master/otree/session.py#L175
>
> > On Jun 12, 2015, at 10:45 AM, Juan BC <notifications@github.com> wrote:
> >
> > where is the code in the core that do that?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/321#issuecomment-111323324>
> .
>
-- 

Juan BC (from phone)
