### ISSUE TITLE
points name should be configurable

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#323]
Hi,

It seems that if `USE_POINTS = True` then it will always write points.  Maybe I want to call my points `₣`.  I don't want to use a real currency, 'cause I pay in Euros.

If it is configurable already, it should be documented in the manual in 7.9.2.

Thanks,

**Comment by oTree-org** [comment]
Agreed this should be configurable. We could add a setting `POINTS_NAME` or `POINTS_LABEL`.

@leliel12 or @alexsanduk feel free to self-assign.

P.S.:

* We could also consider pluralizing "points" (currently it says "1 points").
* Once we localize oTree we should make sure to localize the word "points".

**Comment by oTree-org** [comment]
Actually I will fix this.

**Comment by oTree-org** [comment]
Upon investigation this is more complex. Will re-examine after some other features are developed.

**Comment by oTree-org** [comment]
I found a way to do this.

**Comment by oTree-org** [comment]
Fixed via https://github.com/oTree-org/otree-core/commit/e2b2ee9a3036ba493de1d80677b2ed5825abe9ef.

Added settings POINTS_CUSTOM_NAME and POINTS_CUSTOM_FORMAT.

Should add to docs at some point.
