### ISSUE TITLE
step size for currencies should be configurable

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#324]
Hi,

In `BaseMoneyInput` of `otree/forms/widgets.py` `steps` seems hard-coded to `0.01`.  It's not obvious for me how to change it at least.  

It's added to currency input boxes, which is very nice.  But perhaps currency units are integers? (If using very low exchange rate)

So step should be configurable in `Constants`.

BTW: There's a big chance I missed something!

**Comment by oTree-org** [comment]
What behavior are you trying to change? Something about how the web browser displays or validates these fields?

Currently points must be integers, so if the user submits a float value, they will be asked to fix the error. though I plan to allow a POINTS_DECIMAL_PLACES setting.

**Comment by pank** [comment]
oTree-org <notifications@github.com> writes:

> What behavior are you trying to change? Something about how the web
> browser displays or validates these fields?

A formfield reference pointing to a currency field will insert something
like

```
<input name="shares_buy_price" required="" step="0.01" id="id_shares_buy_price" min="0" class="form-control" type="number">
```

Note the `step`.  Try to click up-arrow in such a field.  It changes by 0.01.


-- 
This space is left intentionally blank

**Comment by leliel12** [comment]
I sugest use the mailing list for this questions. Because the issues is for
a reproducible bugs of feature request

On Tue, 2 Jun 2015 at 17:31 pank <notifications@github.com> wrote:

> oTree-org <notifications@github.com> writes:
>
> > What behavior are you trying to change? Something about how the web
> > browser displays or validates these fields?
>
> A formfield reference pointing to a currency field will insert something
> like
>
> ```
> <input name="shares_buy_price" required="" step="0.01"
> id="id_shares_buy_price" min="0" class="form-control" type="number">
> ```
>
> Note the `step`. Try to click up-arrow in such a field. It changes by 0.01.
>
>
> --
> This space is left intentionally blank
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/324#issuecomment-108089771>
> .
>
-- 

Juan BC (from phone)

**Comment by pank** [comment]
Juan BC <notifications@github.com> writes:

> I sugest use the mailing list for this questions.  Because the issues is
> for a reproducible bugs of feature request

Sorry.  I don't really understand.  There's a good chance I missed
something...

0. I though there was not a mailing list yet﻿...

1. If currencies are integers, then it would seem a bug that the step-size
   is hardcoded to float.  Irrespective of whether steps are configurable
   or not.  At the very least it should be hardcoded to unity, no?

-- 
When the facts change, I change my mind. What do you do, sir?

**Comment by oTree-org** [comment]
I'll work on getting the mailing list set up.

**Comment by leliel12** [comment]
https://groups.google.com/forum/#!forum/otree <<< we are redy has one

On Tue, 2 Jun 2015 at 17:46 oTree-org <notifications@github.com> wrote:

> I'll work on getting the mailing list set up.
>
> > On Jun 3, 2015, at 3:42 AM, pank <notifications@github.com> wrote:
> >
> > Juan BC <notifications@github.com> writes:
> >
> > > I sugest use the mailing list for this questions. Because the issues is
> > > for a reproducible bugs of feature request
> >
> > Sorry. I don't really understand. There's a good chance I missed
> > something...
> >
> > 0. I though there was not a mailing list yet﻿...
> >
> > 1. If currencies are integers, then it would seem a bug that the
> step-size
> > is hardcoded to float. Irrespective of whether steps are configurable
> > or not. At the very least it should be hardcoded to unity, no?
> >
> > --
> > When the facts change, I change my mind. What do you do, sir?
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/324#issuecomment-108093764>
> .
>
-- 

Juan BC (from phone)

**Comment by oTree-org** [comment]
Ah! Great :)

**Comment by pank** [comment]
Juan BC <notifications@github.com> writes:

> https://groups.google.com/forum/#!forum/otree <<< we are redy has one

Juan, can you add gmane support for it, please?

      http://gmane.org/subscribe.php

I prefer to keep mail in my MUA.

Also, does it work without googles membership?

Rasmus

-- 
Need more coffee. . .

**Comment by leliel12** [comment]
I dont think so. Icurrently on the road until tomorrow morning (gmt-3) but
if you want you can delete the Google group

Juan BC (sent from my phone)

**Comment by pank** [comment]
Juan BC <notifications@github.com> writes:

> I dont think so.

If somebody knows what the mailing list email address is I can try to fill
it out.  When I go to the link it's in Dutch (it seems, not German for
sure).  I don't know how to change it.

> but if you want you can delete the Google group

As long as there's a NNTP backend I'm happy...  Gmane is the easiset way
to add it to googles groups, I think.

-- 
I hear there's rumors on the, uh, Internets. . .

**Comment by oTree-org** [comment]
otree@googlegroups.com

@pank , can you send me an email at chris@otree.org so I have your email address?

**Comment by pank** [comment]
oTree-org <notifications@github.com> writes:

> otree@googlegroups.com

I made a request to add the otree list to gmane.comp.python.otree.

Rasmus

-- 
The second rule of Fight Club is: You do not talk about Fight Club

**Comment by pank** [comment]
> otree@googlegroups.com

Sending a mail that address, I got this reply:

> We're writing to let you know that the group you tried to contact (otree) may not exist, or you may > not have permission to post messages to the group. A few more details on why you weren't able to post:

> * You might have spelled or formatted the group name incorrectly.
> * The owner of the group may have removed this group.
> * You may need to join the group before receiving permission to post.
> * This group may not be open to posting.

**Comment by oTree-org** [comment]
Fixed a while back with `POINTS_DECIMAL_PLACES` setting

**Comment by pank** [comment]
oTree-org <notifications@github.com> writes:

> Fixed a while back with `POINTS_DECIMAL_PLACES` setting

Thanks.

Rasmus
