### ISSUE TITLE
formfield should allow empty label

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#325]
Hi,

My field in the player table is
```
f  = models.CurrencyField(initial=None, min=0)
```
In my template html file I have
```
{% formfield player.pred_sigma_1 with label="" %}
```
Expected outcome is an input box without a label.  Instead, I get the name of the variable where underscores have been replaced by spaces.

Note, I can't escape it with e.g. a zero width space, as a bold colon in inserted irrespectivly.  

For the context I have a tabel like the following one, so labels are very much in the way

```
|          | head a      | head b      |
|----------+-------------+-------------|
| label  1 | [field a-1] | [field b-1] |
| ⋮        | ⋮           | ⋮           |
```

**Comment by oTree-org** [comment]
I saw this before; we should fix.

**Comment by pank** [comment]
Note that the label `" "` will still produce the colon.  I'm not sure if this is a feature or a bug, but to be it would seem more natural to test if the `label.strip()` is the empty string.

**Comment by varunsatish** [comment]
Just reiterating for anyone who is reading this (this took me a long time to realise). You need to set label = "", not label = " ". That is, do not leave the space within the string.
