### ISSUE TITLE
CurrencyInput is always blank, even if the field has a non-null value in the DB

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#326]
`CurrencyField`/`CurrencyInput` has a bug where the current value is not displayed as an initial value in the input widget, unlike `PositiveIntegerField`.

I have a field that is defined as

```
    shares_buy_price = models.CurrencyField(initial=c(0), min = 0)
    # I also tried initial=0
```

In my template I use

```
   {% formfield player.shares_buy_price with label="for at most per share" %}
```

This field *always* shows up empty, rather than a zero.

**Comment by oTree-org** [comment]
Maybe a bug in `otree.forms.widgets.BaseMoneyInput._format_value`

**Comment by gregmuellegger** [comment]
This only happened when the initial value was `0` (which evaluates to `False` in an if statement). As @oTree-org pointed out, the fix is done in the `_format_value` method. We convert the value there to be a string instead of a decimal now.
