### ISSUE TITLE
Launcher: check for new versions of otree-core

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#331]
It might be good to keep users up-to-date with otree-core, so they have the latest bugfixes and features. We could make the launcher download & install new otree-core versions (and update `requirements_base.txt`).

Considerations:

* We should make it unintrusive, so users do not get frequent pop-ups. Maybe a "check for updates" menu item. Or text in the status bar saying "a new version of otree-core is available"
* Some otree-core updates contain essential fixes, whereas others are minor/unimportant.
* There is a possibility that future updates to otree-core will break backwards compat (though I try to avoid this, and in the past 4-5 months we have not broken compat).
* As long as we don't break compat, we could consider an "auto-update" feature (may an optional setting)
* Users should be able to revert to old versions, e.g. because otree-core updates may contain accidental regressions.

I think something similar to the launcher's `version.json` could be nice.

Interested in opinions on this.

**Comment by leliel12** [comment]
The problem if the user is development one of this deployments and we
sugest a change... I think we need first to define an stable api (something
like version 1.0)

On Thu, 11 Jun 2015 at 23:15 oTree-org <notifications@github.com> wrote:

> It might be good to keep users up-to-date with otree-core, so they have
> the latest bugfixes and features. We could make the launcher download &
> install new otree-core versions (and update requirements_base.txt).
>
> Considerations:
>
>    - We should make it unintrusive, so users do not get frequent pop-ups.
>    Maybe a "check for updates" menu item. Or text in the status bar saying "a
>    new version of otree-core is available"
>    - Some otree-core updates contain essential fixes, whereas others are
>    minor/unimportant.
>    - There is a possibility that future updates to otree-core will break
>    backwards compat (though I try to avoid this, and in the past 4-5 months we
>    have not broken compat).
>    - As long as we don't break compat, we could consider an "auto-update"
>    feature (may an optional setting)
>    - Users should be able to revert to old versions, e.g. because
>    otree-core updates may contain accidental regressions.
>
> I think something similar to the launcher's version.json could be nice.
>
> Interested in opinions on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/331>.
>
-- 

Juan BC (from phone)

**Comment by leliel12** [comment]
i directly connect to *pypi*  to make this evaluations

**Comment by leliel12** [comment]
implemented all the backend services.

**Comment by leliel12** [comment]
The implementation of this feature is on **dev** branch

The step of change the version are:

1. The launcher retrieve the otree-core version installed in the *virtualenv* and all the available versions from *pypi* and create the pop-up

   ![otree launcher - v 0 7 dev_013](https://cloud.githubusercontent.com/assets/299010/8282490/94e8384c-18c7-11e5-8957-c1fa7f82d137.png)

   ![select otree-core version_014](https://cloud.githubusercontent.com/assets/299010/8282494/9a671ea0-18c7-11e5-9dba-0ebaded5f683.png)

2. When you select the new version the  `requirements_base.txt` file from your working project are patched and commit 

   ![console](https://cloud.githubusercontent.com/assets/299010/8282648/98a77910-18c8-11e5-9c9b-01850bd3d712.png)

3. The `requirements_base.txt` file is reinstalled like every time when you change the project

The version `0.7.dev` is ready for testing but i pretend to make more improvements including internationalization.

Also the current version made a lot improves in cache so i reduce the calls over internet for make checks

**Comment by leliel12** [comment]
@oTree-org  please test and if you want some kind of filter on version this can be done

**Comment by leliel12** [comment]
fixed here: https://github.com/oTree-org/otree-launcher/commit/6631fa2de8cbaa42e08f2c307aebcd4bc97b560c
