### ISSUE TITLE
Time spend on each page

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#333]
Hi,

It should be possible to record the time that a participant spends on each page in each round.  This can of course be done on a user-level with javascript.  However, it seems general enough and complicated enough that it should maybe be done on the `otree-core` level.

There's a javascript package [TimeMe.js](https://github.com/jasonzissman/TimeMe.js) under Apache license that might serve this purpose. 

By the way, I was told by an a more experienced colleague to collect this and that apparently it's a standard measure these days.

Rasmus

**Comment by oTree-org** [comment]
We will add this.

**Comment by goblortikus** [comment]
How do we measure time spent per page? Or total time for a game? Sorry I don't get it.

**Comment by oTree-org** [comment]
In the admin interface, on the black header bar, click "Export", and then you will see a link like "Time spent on each page". You can download a CSV with this info.
