### ISSUE TITLE
Timing of filling out fields

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#334]
Hi,

It is desirable to see which order fields are filled out in.  That is for each field on the page, it should be possible to get a time stamp of when it was altered.  IOW: a set like this `((fieldₙ, altered-timeₙ)ᵢ₌₀ᴺ)`.  This is useful to gather hints  as to whether backward induction is utilized.

As with #333 it can be done on a user level, but it seems tedious and common enough that it could be 
in `otree-core`.  Again, the request follows from discussing my current project with a more experienced colleague.

Rasmus

**Comment by oTree-org** [comment]
We don't have resources to implement in this milestone. Will reexamine later.
