### ISSUE TITLE
shouldn't player.payoff be  c(0) initially?

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#337]
Hi,

In my code I had something like this in the `Group` class:
```
for p in self.get_players():
    x = c(kappa/max([1,sigma]))
    p.payoff += x
```

This leads to some weird error, which seems to be because the initial value of `player.payoff` is None.  So I had to add something like `p.payoff = max([0, p.payoff])`.  

Is this intentional?

**Comment by leliel12** [comment]
Its for consistency in the database.

i sugest:

```python
for p in self.get_players():
    x = c(kappa/max([1,sigma]))
    p.payoff = x if p.payoff is None else p.payoff + x
```

**Comment by leliel12** [comment]
Also the idea of payoff `None` is really useful for search payoff never used (like dead sessions and something like that. Is really semantically different if something play but win *0* points.

Eventually I gona write a data analysis tool for otree and this None value will be really useful

**Comment by pank** [comment]
It would seem that some other field would be used for this?   E.g. `player._active = None` and the first time some variable is changed `player._active = True`.  

In any case, in the "Money and Points" section of the manual this should be mentioned.  E.g. in 2nd paragraph:

```
... For example, each player has a payoff field, which is a CurrencyField with initial value `None`
```

Or modify `CurrencyField.__add__(self, other)` to work "as expected" when the value is None and other is a number.  (It does sound like an awful hack).

**Comment by leliel12** [comment]
Ok please make an issue report on the otree-docs issue referencing this one

**Comment by oTree-org** [comment]
I prefer to keep the default value `None`. In oTree, fields are `None` by default, so this is consistent. Second, the semantic difference between `None` and 0 -- for example, bots can warn when the payoff was not set.
