### ISSUE TITLE
Groups in previous rounds

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#339]
Hi,

`players.py` has a lot of nice functions to get data from previous rounds.  However, `groups.py` does not seem to offer any way to get outcome variables from previous rounds (say equilibrium prices) cf. [the manual](http://otree.readthedocs.org/en/latest/object_model_and_self.html) (and skimming `groups.py`).  It would be nice to have a `group` version of `in_previous_rounds()`.

I guess it can be access via `subsession.in_*_rounds()`,  but it seems less convenient.

**Comment by pank** [comment]
Actually, it's not clear to me how I would recover the time series of a particular group.  I can presumably do something like 

```
class Subsession(otree.models.BaseSubsession):

    def previous_data(self):
        sessions = self.in_all_rounds()
        group_rounds = {s.round_number: s.get_groups() for s in sessions}

        ## desired outcome
        ##           group_A   group_B  group_C
        ## round 1:  A1         B1       C1
        ## round 2:  A2         B2       C2
        ##   ⋮       ⋮           ⋮       ⋮
        ## round t:  At         Bt       Ct
```

but it's not obvious that I can ensure that the ordering of groups is always identical (so that `group_A` is always index 0 in `s.get_groups()`).  It says `ordering = ['pk']`, but I don't know what that means...

I also see other issues with this approach.   Thus, I'm not sure if the statement 
> I guess it can be access via subsession.in_*_rounds(), but it seems less convenient 

is correct.

**Comment by oTree-org** [comment]
I am thinking about the best way to do this, given that groups can be re-shuffled across rounds.

**Comment by oTree-org** [comment]
Fixed in https://github.com/oTree-org/otree-core/commit/35500a8329adb04203ae3850033c0a49a647810b.
