### ISSUE TITLE
currency field status lost when using django template operations

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#340]
Hi,

I have a CurrencyField `group.equilibrium_price`.   When I use it normally in a template as `{{ group.equilibrium_price }}` it's printed as `42 points`.  However, when I make some "Django template operations" on it, it seems to change type (or at least `points` is no longer printed).  Examples:
```
Multiply by 11: {% widthratio  group.equilibrium_price 1 11 %}
Add 11: {{ group.equilibrium_price|add:11 }}
```
Of course `11` is typically an integer variable.

**Comment by oTree-org** [comment]
you can use the `|c` currency filter like this: `{{ 20|c }}`, resulting in `20 points`. 

But in general doing operations like multiplication etc in templates tends to be flimsy. I recommend instead doing it in `vars_for_templates`.

Closing and applying "next milestone triage" tag (we don't have resources to fix this issue ourselves in this milestone, but will keep around to re-evaluate later).
