### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#341]
Hi,

Another thing that is sometimes provided in experiments is on-screen calculators.  The experiment is probably run in some locked down version of the browser, so participants can probably not use the system calculator.  I think an onscreen calculator might be nice to support out of the box, if the author desires it (I certainly do!).

The MIT licensed [calculator by Keith Wood](https://github.com/kbwood/calculator) seems nice in that it's not intrusive and it works with keyboard inputs.  It can also be standalone and can recall earlier values and show previous inputs (show formula) ([see examples](http://keith-wood.name/calculator.html)).  It does not use bootstrap css, however.  Though it does have styling support so maybe it can be adapted...

**Comment by oTree-org** [comment]
Will revisit this in a later milestone. For now, game programmers can modify `_templates/global/Base.html` to add a calculator widget themselves.
