### ISSUE TITLE
Bots: problem if a participant has 2 submits in PendingBuffer

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#342]
The bots break for a few games. It seems to be those that have many wait pages, or multiple wait pages in a row. See **lemon_market** in oTree-library or **multi_player_game** in otree-core.

I investigated and think I found the reason.

If a bot is blocked, then we keep adding their submits to the `PendingBuffer`, so the same bot may have 2 items in the buffer. Then the code loops through all items in the buffer and tries to submit each. The problem is that if the bot's 1st submit did not succeed (because of a wait page), then we should not submit the 2nd one.

I solved this temporarily by keeping track of which bots have already been seen in the current loop iteration and skipping them:

```python
while pending or submit_groups:
            seen_bots = set()
            for submit, attempts in pending:

                if attempts > MAX_ATTEMPTS:
                    msg = "Max attepts reached in  submit '{}'"
                    raise AssertionError(msg.format(submit))
                if not submit.bot in seen_bots and submit.execute():
                    pending.remove(submit)
                else:
                    seen_bots.add(submit.bot)
```

However, I do not know if this is the best way to really fix the problem, so I am logging this issue.

**Comment by leliel12** [comment]
I applied your patch is the better way to fix this
