### ISSUE TITLE
ImportError: No module named otree_launcher

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#346]
I got this report from 2 users in the past few days:

> When trying to run the launcher on my Macbook, I get the following error:

```bash
Ians$ bash /Users/Ians/Downloads/otree-launcher-master/otree.sh 
Traceback (most recent call last):
 File "<string>", line 1, in <module>
ImportError: No module named otree_launcher
```

From another user:

> I am having trouble installing oTree on my Windows computer. After having installed Python, I am still unable to run – as administrator – the launcher. Precisely, the terminal says that the otree_launcher module is not found.

> Note that when I tried to install oTree on Ubuntu 14.4, it worked perfectly.

Both users have Python 2.7 installed.

**Comment by leliel12** [comment]
screenshots of errors in diferent OS
![screenshot - 300615 - 20 20 06](https://cloud.githubusercontent.com/assets/299010/8444468/4053df92-1f67-11e5-8414-f00770bb5068.png)
![0](https://cloud.githubusercontent.com/assets/299010/8444470/46959918-1f67-11e5-97d1-d4fb19f6afb2.png)

**Comment by leliel12** [comment]
The problem is because the `bat` the `exe` and the `sh` dont change the path to execute the launcher so python can detect where is the *otree launcher* is located

**Comment by leliel12** [comment]
fixed here: https://github.com/oTree-org/otree-launcher/commit/6631fa2de8cbaa42e08f2c307aebcd4bc97b560c
