### ISSUE TITLE
TemplateEncodingError: Templates can only be constructed from unicode or UTF-8 strings

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#347]
3 users have reported this error to me; is there anything we can do to avoid/fix it?

User 1:

> After I tried to include an image into a template and saved a .png file wrongly into the templates/ instead of /static folder, the oTree Launcher returns an error saying 

```
File "C:\Users\Robin\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\django\template\base.py", line 128, in __init__
     raise TemplateEncodingError("Templates can only be constructed "
 django.template.base.TemplateEncodingError: Templates can only be constructed from unicode or UTF-8 strings.
```

>Even if I substitute all files in the oTree folder with files that worked before it still returns that error when triying to launch otree.

> I am using PyCharm.

User 2:

> Unfortunately, any change I make (even if it is only the text in a template of one of the sample treatments) leads to a crash of otree which I can only get running again if I delete otree altogether and reinstall it. 

> The console says:

```
django.templates.base.TemplateEncodingError: Templates can only be constructed from unicode or UTF-8 strings
```

> I am using TextWrangler and the default encoding is Western (Mac OS Roman). 

User 3:

> I got this error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/autoreload.py", line 222, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 105, in inner_run
    self.validate(display_num_errors=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 362, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 371, in check
    all_issues = checks.run_checks(app_configs=app_configs, tags=tags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/checks/registry.py", line 59, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/otree/checks/__init__.py", line 159, in wrapper
    func(rules, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/otree/checks/__init__.py", line 245, in templates
    rules.template_has_no_dead_code(template_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/otree/checks/__init__.py", line 45, in wrapper
    res = meth(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/otree/checks/__init__.py", line 115, in template_has_no_dead_code
    compiled_template = Template(f.read())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/base.py", line 128, in __init__
    raise TemplateEncodingError("Templates can only be constructed "
django.template.base.TemplateEncodingError: Templates can only be constructed from unicode or UTF-8 strings.
```

> I was using Pycharm v2 and the settings were set to UTF-8.

**Comment by leliel12** [comment]
relevant: https://docs.djangoproject.com/en/1.8/ref/unicode/#templates

On Wed, 1 Jul 2015 at 13:24 oTree-org <notifications@github.com> wrote:

> 3 users have reported this error to me; is there anything we can do to
> avoid/fix it?
>
> User 1:
>
> After I tried to include an image into a template and saved a .png file
> wrongly into the templates/ instead of /static folder, the oTree Launcher
> returns an error saying
>
> File "C:\Users\Robin\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\django\template\base.py", line 128, in __init__
>      raise TemplateEncodingError("Templates can only be constructed "
>  django.template.base.TemplateEncodingError: Templates can only be constructed from unicode or UTF-8 strings.
>
>  Even if I substitute all files in the oTree folder with files that
> worked before it still returns that error when triying to launch otree.
>
> I am using PyCharm.
>
> User 2:
>
> Unfortunately, any change I make (even if it is only the text in a
> template of one of the sample treatments) leads to a crash of otree which I
> can only get running again if I delete otree altogether and reinstall it.
>
> The console says:
>
> django.templates.base.TemplateEncodingError: Templates can only be constructed from unicode or UTF-8 strings
>
>  I am using TextWrangler and the default encoding is Western (Mac OS
> Roman).
>
> User 3:
>
> I got this error:
>
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/autoreload.py", line 222, in wrapper
>     fn(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 105, in inner_run
>     self.validate(display_num_errors=True)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 362, in validate
>     return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 371, in check
>     all_issues = checks.run_checks(app_configs=app_configs, tags=tags)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/checks/registry.py", line 59, in run_checks
>     new_errors = check(app_configs=app_configs)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/otree/checks/__init__.py", line 159, in wrapper
>     func(rules, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/otree/checks/__init__.py", line 245, in templates
>     rules.template_has_no_dead_code(template_name)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/otree/checks/__init__.py", line 45, in wrapper
>     res = meth(self, *args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/otree/checks/__init__.py", line 115, in template_has_no_dead_code
>     compiled_template = Template(f.read())
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/base.py", line 128, in __init__
>     raise TemplateEncodingError("Templates can only be constructed "
> django.template.base.TemplateEncodingError: Templates can only be constructed from unicode or UTF-8 strings.
>
>  I was using Pycharm v2 and the settings were set to UTF-8.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/347>.
>
-- 

Juan BC (from phone)

**Comment by gregmuellegger** [comment]
I proposed a check for this in #360.
