### ISSUE TITLE
otree version show only django version

### ISSUE THREAD

**Issue by leliel12** [oTree-org/otree-core#353]
I have more than five otree virtual envs and the only way to know what version of otree is installed is throught `pip list` or `pip freeze` because when you do 

```bash
$ otree --version
1.7.7
$ otree version
1.7.7
```
you always has the django version.

I spect something more useful like

```bash
$ otree version
oTree: 0.3.9 - Django: 1.7.7
```

**Comment by oTree-org** [comment]
Yes sounds good
