### ISSUE TITLE
Waiting on Player

### ISSUE THREAD

**Issue by seidelj** [oTree-org/otree-core#354]
on version otree-core==0.3.3 I experienced a player advance to new round while the 3 other players were stuck on the previous round and waiting for the player first mentioned( who was then also stuck waiting for the other 3 players).

I don't have a stacktrace for the error.  I was running on a production server and heroku's logs ate it up (just added logentries).  It has also never been detected in any tests using bots locally.

I've upgraded to the latest version but wondering if this is anything related to a known issue.

**Comment by oTree-org** [comment]
Known issue fixed a couple of weeks ago, upgrade to the latest oTree-core

**Comment by seidelj** [comment]
can do. will do. thanks for the response.
