### ISSUE TITLE
NumberInput: only integers can be entered

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#356]
Try playing the `public_goods_simple` game in `number-input-bug` branch, and entering non-integer numbers like 0.05 in the CurrencyField, DecimalField, and FloatField. (diff [here](https://github.com/oTree-org/oTree/commit/cdc831616a8e8471c7924ed1583e239cd329d7ae))

The browser's validation doesn't allow these numbers because apparently the `step` attribute is omitted from the HTML and defaults to 1.

I tested on an oTree-core commit from the end of May (0d5687a341da5a3419cf06f7374f5bd298d40278) and this error reproduced then as well.
However, I remember it used to work a while back.

I don't know why this happens. As far as I understand, the `DecimalField` passes the `step` kwarg to the widget:

https://github.com/django/django/blob/11cac1bd8ef7546ca32d9969d4348bf412dc6664/django/forms/fields.py#L413

And the `NumberInput` widget should read this: https://github.com/gregmuellegger/django-floppyforms/blob/master/floppyforms/widgets.py#L399

If I explicitly set the `step` attribute on the `NumberInput` class, the step appears to show up in the HTML.

**Comment by oTree-org** [comment]
To reproduce with `CurrencyField`, you need to set `settings.USE_POINTS=False` so that it uses dollars instead of points (points can only be integers).

**Comment by gregmuellegger** [comment]
I think I found the cause for this. It's that django is testing for `isinstance(widget, NumberInput)` where `NumberInput` is Django's implementation but we use floppyforms implementation.

I'll fix this by adding a proper fix to floppyforms. I expect this to happen tomorrow.

**Comment by gregmuellegger** [comment]
I released django-floppyforms 1.5.0 and updated the requirements in otree's `setup.py` to require this version. That fixes this problem. See https://github.com/oTree-org/otree-core/commit/49c6d5c159e1f6adafbc234d955b92a0a79ac99f
