### ISSUE TITLE
Launcher: "Version select" list should be sorted numerically, not alphabetically

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#363]
See image:

![image](https://cloud.githubusercontent.com/assets/5423929/8843872/58aeeed0-3149-11e5-8e31-adab2f4fdf0c.png)

**Comment by leliel12** [comment]
https://github.com/oTree-org/otree-launcher/commit/937217fa37f47505faf5c3cc5948df7854988b63
