### ISSUE TITLE
Add more data to debug info

### ISSUE THREAD

**Issue by leliel12** [oTree-org/otree-core#364]
I currently working in one experimente with some conditions that will be usefull to display in the debug info. 

i suggerst to make some changes to the *debug info* table to show all the current context. With this change in `vars_for_all_templates` you can write something like

```python
def vars_for_all_templates(self):
    context = {'Constants': Constants,  'player': self.player}
    if settings.DEBUG:
        context.update({"Foo": "this will show on the debug"})
```

**Comment by oTree-org** [comment]
That sounds fine to me. The context could be added as extra entries to the current debug info table, or it could be a separate table below the debug info table.

Here is some info to help with implementation.

Here is where the debug info table is defined:
https://github.com/oTree-org/otree-core/blob/17ff689605c812f003a1463a590164c9531f0382/otree/views/abstract.py#L141

Here is `get_context_data`:
https://github.com/oTree-org/otree-core/blob/17ff689605c812f003a1463a590164c9531f0382/otree/views/abstract.py#L642

Note that `Constants`, `player`, `group`, and `subsession` are automatically passed to every template.

**Comment by leliel12** [comment]
I test with many forms to modify this api for make easy to use for anybody, so i dont change anything in `get_debug_values` but now any page can implement `on_debug_show(self)` method.

This method only need to return a dictionary (`dict`) with the extra data to add into debug table. All the logic to append this data to the original one is implementhed in the `otree.middleware` module (https://github.com/oTree-org/otree-core/blob/e58d9ea530599508f361902d534927d7fd329b1f/otree/middleware.py)

When a new version of otree-core is published i gonna add a paragrahp in the documentation

**Comment by leliel12** [comment]
reopen for change the behavior

**Comment by oTree-org** [comment]
I will experiment with this.

**Comment by leliel12** [comment]
http://awesomescreenshot.com/07d53sb907 in the last commit i added this

**Comment by leliel12** [comment]
probably we can close the ticket now. This changes are already n the last 2 or 3 versions
