### ISSUE TITLE
RadioSelectHorizontal widget show normal text and RadioSelect uses bold

### ISSUE THREAD

**Issue by leliel12** [oTree-org/otree-core#368]
RadioSelectHorizontal widget show normal text and RadioSelect uses bold

![questionaire 2015-07-29 14-44-12](https://cloud.githubusercontent.com/assets/299010/8965251/a4ce6b54-3600-11e5-9725-5720f5ab2318.png)

**Comment by oTree-org** [comment]
I guess we should change RadioSelect to use non-bold text.
