### ISSUE TITLE
Launcher should use "otree" command rather than "python otree"

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#369]
Now that we have an `otree` console script on the path, we don't need the `./otree` script in the project root anymore.

Before we delete it, we need to update the launcher to use `otree` instead of `python otree`:

https://github.com/oTree-org/otree-launcher/search?utf8=%E2%9C%93&q=%22python+otree%22

**Comment by leliel12** [comment]
**WARNING** 0.7.7 is now mandatory for encourage the use of `otree` over `python otree`

fix on https://github.com/oTree-org/otree-launcher/commit/93617813240b3930de3d32f6fcb4dfb8bf6c3c8e
