### ISSUE TITLE
Prevent assignment to Constants

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#370]
I saw a user modifying `Constants` at runtime, e.g. in `views.py`:

```
def after_all_players_arrive(self):
    Constants.foo = True
```

Of course this can cause problems because (1) `Constants` is by design only supposed to hold constants, and (2) `Constants` is a global variable whose state is shared across all sessions as long as the server is running.

My suggestion is that we make `Constants` inherit from a "`BaseConstants`" class in otree-core, and put some logic in `BaseConstants` that prevents assigning to an attribute outside of the class definition (either new or existing attributes). I believe it is possible to do this by modifying the metaclass.

For example:

```
class Constants(otree.BaseConstants):
    a = 1

Constants.a = 2 # should raise an exception
Constants.b = 2 # should raise an exception
```

**Comment by leliel12** [comment]
i get that one :D

On Fri, 31 Jul 2015 at 00:06 oTree-org <notifications@github.com> wrote:

> I saw a user modifying Constants at runtime, e.g. in views.py:
>
> def after_all_players_arrive(self):
>     Constants.foo = True
>
> Of course this can cause problems because (1) Constants is by design only
> supposed to hold constants, and (2) Constants is a global variable whose
> state is shared across all sessions as long as the server is running.
>
> My suggestion is that we make Constants inherit from a "BaseConstants"
> class in otree-core, and put some logic in BaseConstants that prevents
> assigning to an attribute outside of the class definition (either new or
> existing attributes). I believe it is possible to do this by modifying the
> metaclass.
>
> For example:
>
> class Constants(otree.BaseConstants):
>     a = 1
>
> Constants.a = 2 # should raise an exception
> Constants.b = 2 # should raise an exception
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/370>.
>
-- 

Juan BC (from phone)

**Comment by leliel12** [comment]
After the publication of the new version we can change a

**Comment by leliel12** [comment]
After the publication of the new version we can change all the constants declararion for this one:

```python
class Constants(otree.models.BaseConstants):
    ....
```
