### ISSUE TITLE
Bots: static content fails to load with Whitenoise library

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#371]
See the Travis error:

https://travis-ci.org/oTree-org/oTree/builds/73842221#L402

This break seems to be caused by this line (if i remove it, the bots work fine):

https://github.com/oTree-org/otree-core/blob/f57e9030ccd9111a54cd0545c519e1c8f30ea54d/otree/settings.py#L202

We recently switched to use [Whitenoise](https://pypi.python.org/pypi/whitenoise) to serve our static content, and use Gzip compression to improve performance.

Should we disable Gzip compression when the bots run? Not sure exactly why this problem is occurring.

**Comment by leliel12** [comment]
yes/no the problem is the gzip.

To guarantee the correct functionality of whitenoise we need to first run `otree collectstatic` because whitenoise is not design for run under development mode.

http://whitenoise.readthedocs.org/en/latest/django.html <-- reference

**Comment by leliel12** [comment]
as first attempt i gonna try to disable the "staticfile storage" only on test run
