### ISSUE TITLE
Next button should be classed

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#374]
Hi,

I have been asked to move the next button to the right of the page.  The code is something like
```
<p>
    <input class="btn btn-primary btn-large btn-primary" value="Next" type="submit"></input>
</p>
```

It would be great if the `p` and the input had some `class` or `id` so that they could easily be styled.

Rasmus

**Comment by oTree-org** [comment]
I recently added the class `next-button` to the `input` element; upgrade to >=0.3.32 and let me know if there are any issues.
