### ISSUE TITLE
Launcher "run server": browser opens to error page

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#375]
When I click the launcher's "run server" button, it opens to an error page:

![image](https://cloud.githubusercontent.com/assets/5423929/9294670/5bf41d46-448f-11e5-8cef-748617c03bd8.png)

(On Firefox, resolves if you wait a few seconds then refresh the page)

![image](https://cloud.githubusercontent.com/assets/5423929/9294674/852a5b08-448f-11e5-8ec6-1d76a2636ba6.png)

(On Chrome, the page refreshes automatically after 5-10 seconds, and loads correctly.)

I guess that at the moment the browser is launched, the server is not ready yet?

(Reproduces on Windows with Chrome or Firefox, not sure about other environments)

**Comment by leliel12** [comment]
This problem was already solved from the first version. The lancher wait 5
seconds until open the browser. I can sugest add an static page to rhe
launcher that checks wheb the server is runing. I thinks this gonna work

El dom, ago 16, 2015 15:27, oTree-org <notifications@github.com> escribió:

> When I click the launcher's "run server" button, it opens to an error page:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5423929/9294670/5bf41d46-448f-11e5-8cef-748617c03bd8.png>
>
> (On Firefox, resolves if you wait a few seconds then refresh the page)
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5423929/9294674/852a5b08-448f-11e5-8ec6-1d76a2636ba6.png>
>
> (On Chrome, the page refreshes automatically after 5-10 seconds, and loads
> correctly.)
>
> I guess that at the moment the browser is launched, the server is not
> ready yet?
>
> (Reproduces on Windows with Chrome or Firefox, not sure about other
> environments)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/375>.
>
-- 

Juan BC (from phone)

**Comment by oTree-org** [comment]
OK sounds like a good plan.

**Comment by leliel12** [comment]
fix on https://github.com/oTree-org/otree-launcher/commit/7ba54d450d08d3ce9bac24b87780cfe5985485a7
