### ISSUE TITLE
Launcher: otree.sh has problems related to file path

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#379]
Bug reported by user:

> on the mac, the launcher install instruction to "open the terminal and run bash otree.sh" does not seem to work for me. I found that I have to specify the file path in order for this to work. Additionally, the file path does not work when the folder names contain spaces.

**Comment by leliel12** [comment]
i don't understand what is "specify" the file path?

if you are in your home directory `~` and you already downloaded *oTree Launcher* in `~/otree` then the alternatives are:

```shelscript
bash otree/otree.sh
```

or


```shelscript
cd otree
bash otree.sh
```

**Comment by leliel12** [comment]
please check the version `0.7.13`
