### ISSUE TITLE
Launcher: replace .bat with .py

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#380]
I sometimes get an antivirus warning when I click the .bat. Instead, we should just use a .py file to start the launcher.

(As discussed over email)

**Comment by oTree-org** [comment]
We should consider whether we can also replace `otree.sh` by a `.py` script (which would hopefully fix #379).

**Comment by leliel12** [comment]
https://github.com/oTree-org/otree-launcher/commit/ffc405e06dfec0eaa5d77d6c91f113a2a451e035
