### ISSUE TITLE
Launcher doesn't open browser on Mac OSX

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#381]
Reported by a user:

> I just noticed (and my co-author just confirmed me) that under macosx, the version 0.7.12 of the otree launcher does not launch the browser when one clicks play after cleaning the database.
Versions 0.7.11 and below work correcly

(I just tried on Windows and it works fine for me.)

**Comment by leliel12** [comment]
sadly this is a problem of python itself and fails in some instances of osx. (probably is the configuration of osx, the browser or osascript)

References:
- http://stackoverflow.com/questions/8812619/cant-launch-a-web-browser-in-os-x-via-open-new-works-fine-on-windows
- http://stackoverflow.com/questions/1997327/am-i-using-the-webbrowser-open-wrong-or-does-it-not-work-as-advertised-pyth

**Comment by leliel12** [comment]
as note: i experienced some of this problems in linux, and i trying to write my own module to open webpages of the oTree  Launcher, this generate more problems and eventually i going back to webbrowser module of python standar lib

**Comment by leliel12** [comment]
after more research more bugs about the osx and open browser showup

https://bugs.python.org/issue24452
https://github.com/mkdocs/mkdocs/issues/465
