### ISSUE TITLE
Rewrite the resetdb command to be database-independent

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#382]
The `resetdb` command deletes the database, and then runs the Django `migrate` command.

Currently, it only works on SQLite (where it deletes the DB file), and on Heroku (where it uses the special Heroku command to erase the DB). It doesn't work on non-Heroku servers.

We should rewrite it in a database-agnostic way. The benefits are (1) this would work on any server, e.g. Linux/MySQL, and (2) we could then eliminate the `otree-heroku` script [here](https://github.com/oTree-org/otree-core/blob/master/otree/management/deploy/heroku.py), which basically only exists because of the special-case `resetdb` code. 

Then, instead of doing `otree-heroku resetdb`, users would just use the standard `heroku run` command like this: `heroku run otree resetdb`.

It should be possible to rewrite in a database-independent way using Django management commands: we run [sqlclear](https://docs.djangoproject.com/en/1.8/ref/django-admin/#sqlclear-app-label-app-label) for all apps, and then pipe the output to [dbshell](https://docs.djangoproject.com/en/1.8/ref/django-admin/#dbshell).

**Comment by leliel12** [comment]
i already have something like that for another project

**Comment by leliel12** [comment]
The new resetdb is REALLY powerful, not only clear the database also support migrations inside any otree app

**Comment by oTree-org** [comment]
Published to 0.3.37, thanks
