### ISSUE TITLE
Make 'debug info' look nicer

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#384]
I recently refactored the "debug info" section, such as adding support for multiple tables. However, we should have a look to see if we can tweak the CSS/HTML so it looks nicer visually. Maybe have a look at the colors/formatting. Also, it seems long text in the table cells does not wrap properly.

**Comment by leliel12** [comment]
the text only wraps if we have more than 1 word

**Comment by leliel12** [comment]
![survey 2015-10-06 19-37-22](https://cloud.githubusercontent.com/assets/299010/10324667/c8b8d800-6c61-11e5-9671-699edcc49ee7.png)

**Comment by leliel12** [comment]
Testing in: firefox (linux and windows), chrome and ie(11)
