### ISSUE TITLE
manage.py resetdb: error: unrecognized arguments: --noinput

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#385]
The launcher calls `otree resetdb --noinput`, but it seems the new `resetdb` command does not support `--noinput`:

```
> Resetting (please wait)...
> Install done
> usage: manage.py resetdb [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
>                          [--pythonpath PYTHONPATH] [--traceback] [--no-color]
> manage.py resetdb: error: unrecognized arguments: --noinput
```

We should fix in a way that minimizes compat issues for users with an older version of the launcher, or an older version of otree-core.

**Comment by oTree-org** [comment]
While we wait for a fix for this, I temporarily bumped the otree-core version in library's requirements_base.txt down to 0.3.36 (before new resetdb was implemented).

**Comment by leliel12** [comment]
done
