### ISSUE TITLE
Currency amounts don't get displayed if currency code has non-ASCII character

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#387]
Repro steps:

- Set `USE_POINTS = False`
- Set `REAL_WORLD_CURRENCY_CODE = 'EUR'`
- Run server and display a page that has a currency amount (e.g. public goods simple).

Currency amounts are not printed: e.g. "You made ." instead of "You made €100".

If using USD or CHF (which use the ASCII symbols "$" and "CHF"), the problem does not occur.

I guess this is caused by how the currency is formatted, somewhere here: https://github.com/oTree-org/otree-core/blob/master/otree/common.py#L25

**Comment by leliel12** [comment]
https://github.com/oTree-org/otree-core/blob/master/tests/test_currency.py <<< this test execute the validation. In this bug we hit a potential bug of django
