### ISSUE TITLE
"otree startapp" doesn't use oTree app template, uses default Django app template

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#394]
This occurred for 2 users with otree 0.3.43/44 on Mac OSX, with virtualenv.

`otree startapp myapp` just creates a standard Django app. For example, the contents of models.py are:

```
from django.db import models

# Create your models here.
```

It works fine for me on Windows, either using the oTree launcher, or my dev installation of oTree-core.

Maybe related to #388?

**Comment by leliel12** [comment]
I think i fix this in the last commit can anyone check this please

**Comment by oTree-org** [comment]
Fixed in https://github.com/oTree-org/otree-core/commit/bd1ef19fc5735ae110ad3c4c606f9bcb4fc91b1b
