### ISSUE TITLE
Ajax Sequence

### ISSUE THREAD

**Issue by leliel12** [oTree-org/otree-core#397]
In some cases, will be need some dynamic content into otree.

I sugest to add 2 components to public api:

- `AJAX` Class into `._builin`
- `ajax` list 

The first one can redefine the `process(self, data)` method that receive a parsed *JSON* data from client-side, and return a dictionary serialized to the front end
The second one is a *page_sequence* like mechanism to register an ajax view.

Example:

```python
class UpdateSomething(AJAX):

     def process(self, data):
         self.player.data0 = data["data0"] # we can access player like any page
         return {"from server": "ok"}

ajax = [UpdateSomething]

```

Also we can add some javascript helper like

```html
<script>
    oTree.ajax("experiment", "UpdateSomething", {data0: "foo"}, function(data){
          console.log(data["from_server"]); // this will be print "ok"
    });
</script>
```

**Comment by leliel12** [comment]
Maybe we can make a more easy *js*  api like from django-dajaxice.

```python
oTree.matching_pennies.UpdateSomething({data0: "foo"}, function(data){
      console.log(data["from_server"]); // this will be print "ok"
});
```

**Comment by oTree-org** [comment]
Yes I think this is an interesting idea and oTree needs this eventually. Let's keep thinking about this and discuss design ideas.

**Comment by leliel12** [comment]
i close this issue because i think the #469 its more easy to understand for the oTree users
