### ISSUE TITLE
Add to checks: models.py needs FK to Group and Subsession

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#399]
In an app's `models.py`, `Player` and `Group` need foreign keys, like this:

```
class Group(BaseGroup):
    # <built-in>
    subsession = models.ForeignKey(Subsession)
    # </built-in>


class Player(BasePlayer):
    # <built-in>
    subsession = models.ForeignKey(Subsession)
    group = models.ForeignKey(Group, null = True)
    # </built-in>
```

Several users got errors because they deleted these properties by mistake, and got an uninformative error message: http://i.imgur.com/5seZCsr.png

We should add a check to `otree.checks` (around [here](https://github.com/oTree-org/otree-core/blob/master/otree/checks/__init__.py#L253) in the code) that makes sure these FKs exist.

(Side note: A totally different solution would be to add these foreign keys to `BaseGroup` and `BasePlayer` in in otree-core as `GenericForeignKey`s, so that the user's app doesn't need to include them at all. If someone feels we should do this instead, we can have a discussion about the pros/cons.)

**Comment by leliel12** [comment]
I think the best alternative is add as `GenericForeignKey`

**Comment by oTree-org** [comment]
A few things to keep in mind, if we decide to use the alternative approach (remove the FK from `models.py`):

- We should make this change without breaking user's existing apps (which already contain the FKs directly in `models.py`)
- `GenericForeignKey` have certain limitations. They may be slower than regular FKs, and also do not work with `filter()` and `get()`. Our existing code for `get_players()` follows the FK backwards (i.e. `player_set.all()`); I don't know whether this works with `GenericForeignKey`. Maybe we can instead use a regular foreign key, but add it to the model at runtime.
- Removing the FK from the user's `models.py` would reduce the ability of certain IDEs to autocomplete code. In PyCharm, if I'm in the `Player` model and write `self.group.`, PyCharm recognizes that `group` is a FK and shows me the available fields and methods on the `Group` model. Not all users use IDEs, but we should consider this.

Thoughts?

**Comment by leliel12** [comment]
After some code reading i think the best aproach is to maintain the "explicit" foreign key.
