### ISSUE TITLE
"otree" command is slow

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#405]
Recently it seems the `otree` command has become slow. On my PC, entering `otree` at the command line takes at least 10 seconds before any output is shown.

**Comment by leliel12** [comment]
Can you please run 10 times otree with the same command and take the average time?

**Comment by leliel12** [comment]
And to be honest the slow past of otree command is the django enviroment setup. This is is really slow

**Comment by oTree-org** [comment]
I tried on Mac OSX and it's much faster. Maybe only a Windows problem, or specifically my PC

**Comment by oTree-org** [comment]
Seems to be a general problem on Windows, other people's computers also

**Comment by leliel12** [comment]
i can make a profiling analysis on windows if you think this is important. But probaby the most slow part is django rater than otree

**Comment by oTree-org** [comment]
Seems to be faster on Py3, at least on my PC

**Comment by BertrandBordage** [comment]
Using Ubuntu 14.04 on my computer it takes 1-2 s.

**Comment by oTree-org** [comment]
Yes I am not having problems with this anymore, although it is slower on Windows.
