### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by gregmuellegger** [oTree-org/otree-core#411]
We should do some testing if we can support Django 1.9

**Comment by gregmuellegger** [comment]
Currently if we test against Django 1.9, we get an error from the `django-idmap` package. I created an issue for this with their bugtracker. Let's see how they respond: https://bitbucket.org/tkhyn/django-idmap/issues/1/django-19-support

I created the `django1.9` branch for integrating with Django 1.9

**Comment by leliel12** [comment]
Please don't remove the django 1.8 compatibility i gonna add a tox test case for every supported django version.

**Comment by gregmuellegger** [comment]
Yes the plan was to keep Django 1.8 as the mainly advertised Django version that users should use, as it's a long term support release. I've already added the additional tox case here: https://github.com/oTree-org/otree-core/blob/django1.9/tox.ini

**Comment by leliel12** [comment]
Now you can make the test run on django1.9 with the next commands

```bash
$ tox -e py2.7-django1.9-unittest py2.7-django1.9-integration
```

Also you can check the integration with the last version of https://github.com/oTree-org/otree repo

```bash
$ tox -e py2.7-django1.9-unittest py2.7-django1.9-experiments
```

Obviously you can change 1.9 for 1.8

**Comment by gregmuellegger** [comment]
Cheers. idmap added support for Django 1.9 in version 0.4.0. I've upgrade the dependency to list idmap>=0.4.0 in `master`.

Now the package `handy` (it provides the JSONField and PickelField) is not yet compatible. I created this issue with the project: https://github.com/Suor/handy/issues/14
