### ISSUE TITLE
"otree startproject" should work without a settings.py in current dir

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#422]
As described in #421 I implemented a `startproject` command in [otree.management.commands.startproject](https://github.com/oTree-org/otree-core/blob/master/otree/management/commands/startproject.py).

`startproject` is different from other management commands because it is intended to be run from outside a project directory (unlike other commands which should be run from inside the directory containing settings.py).

I attempted to write the special case logic here: https://github.com/oTree-org/otree-core/blob/4c971c6487fe2ee8f8841844c0eac2a9cb322c1e/otree/management/cli.py#L160

But it still does not work in the absence of a `settings.py` file. If I just call `settings.configure()`, then the `startproject` command just executes Django's default `startproject` rather than the one I defined in `otree.management.commands.startproject`.

Maybe we should set `DJANGO_SETTINGS_MODULE` to the settings file in `otree.project_template`?

https://github.com/oTree-org/otree-core/blob/master/otree/project_template/settings.py

(Maybe I am misinterpreting the problem, I don't know much about how settings and apps work.)

By the way, in Django, it is not just start project that can be run from any directory, but also other commands like version, help, startapp, makemessages, etc:

https://github.com/django/django/blob/df0a446fd4c864c003e4f941b5b7abd6f10c9427/django/core/management/__init__.py#L291

I wonder if otree should also allow these commands to be run from any directory. (On the other hand, if the user is running `startapp` from outside a project directory, it might be good to warn them.)

**Comment by gregmuellegger** [comment]
Django has the commands like startproject hardcoded, so I didn't find a way to override those (startapp and startproject) in a non-specific way. However I fixed the problem in https://github.com/oTree-org/otree-core/commit/6c69ddb71ed697ad4d4861ddccf2ef23fc0e9862 by introducing the `OVERRIDE_DJANGO_COMMANDS` list in the `cli.py` module.

Have a look, your startproject command should be picked up now as you expect it.

**Comment by oTree-org** [comment]
Fixed
