### ISSUE TITLE
Otree ultimatum game

### ISSUE THREAD

**Issue by roiorlan** [oTree-org/otree-core#426]
Hi,

I'm new in python and I'm  writing my own ultimatum game for an experiment based on the otree.
I'm trying to change the endowment so it won't be constant but randomized every subsession (i.e round) in the before_session_start method.
Is it possible? 

I want to do something like this:
tried to dosomething like this:
lass Constants(BaseConstants):

    name_in_url = 'ultimatum'
    players_per_group = 2
    num_rounds = 2

    payoff_if_rejected = c(0)
    offer_increment = c(0.5)

class Subsession(BaseSubsession):

    def before_session_starts(self):
        # randomize to treatments
        for g in self.get_groups():
            if 'treatment' in self.session.config:
                g.strategy = self.session.config['treatment'] == 'strategy'
            else:
                g.strategy = random.choice([True, False])
        endowment = c(random.randint(1,6))

    offer_choices = currency_range(0, endowment, Constants.offer_increment)
    offer_choices_count = len(offer_choices)
    keep_give_amounts = [(offer, endowment - offer) for offer in offer_choices]

Thanks.

**Comment by oTree-org** [comment]
The basic approach is right but `endowment` needs to be first defined as a `CurrencyField` on the Subsession, then you assign to `self.endowment`.

Anyway, this type of question is a good fit for the mailing list: https://groups.google.com/forum/#!forum/otree

**Comment by roiorlan** [comment]
Thanks so much!
