### ISSUE TITLE
Slider default fails when the field is currency type

### ISSUE THREAD

**Issue by leliel12** [oTree-org/otree-core#429]
if you has a code like this

```python
class Player(BasePlayer):

    def random_invest():
        return random.randint(0, 100)

    invest = models.CurrencyField(
        min=0, max=100,
        widget=widgets.SliderInput(), default=random_invest)
```

This gona render with a default value of **50** because the html is:

```html
<div data-slider="" class="input-group slider">
    <input type="range" class="form-control" min="0" id="id_invest" step="1" max="100" required="" value="8 points" name="invest">
    <span title="current value" data-slider-value="" class="input-group-addon">50</span>
</div>
```

If you see the `<input type="range"`  element says `value="8 points"` and must be `value="8"`

**Comment by gregmuellegger** [comment]
Unfortunately I wasn't able to reproduce this issue. With the commit 3fa011d I've added tests that are testing for the described issue, but are running fine.

Can you provide some more details on how to reproduce this issue?

**Comment by leliel12** [comment]
i changed the `Player` of **lemon_market** to look like

```python
class Player(BasePlayer):

    # training
    training_buyer_earnings = models.CurrencyField(
        verbose_name="Buyer's period payoff would be", widget=widgets.SliderInput(), default=20)

    training_seller1_earnings = models.CurrencyField(
        verbose_name="Seller 1's period payoff would be", widget=widgets.SliderInput(), default=20)
    ...
```

and when i run the server this look like

![understanding question 1 of 1 - mozilla firefox_001](https://cloud.githubusercontent.com/assets/299010/13416871/b39eced8-df44-11e5-89d2-fde36504fcd8.png)

@gregmuellegger do you have an idea where is the best place to start looking for this behavior?

**Comment by gregmuellegger** [comment]
The value (an Easymoney object) is simply converted to text here and printed, and just printing it contains the currency. We need to convert the money value somehow into a decimal/int/float value to make sense here for the slider widget.

I played around with it and added a `_format_value` method that converts the money value to a decimal. That should fix the issue.

**Comment by gaiagaudenzi** [comment]
Thank you very much leliel12! This solved my problem!
