### ISSUE TITLE
Export specific session

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#431]
hi,

it would be great if one could select a session to download data from.  potentially, it would also be good if the there existed an interface to select which columns to export.  Many are not interesting.  It could for example be a dictionary in the say `models.py` of mappings from column names to export names where a column is dropped if the export name is `None`.

Thanks,
Rasmus

**Comment by oTree-org** [comment]
More of a feature request rather than a bug...feature requests should be sent to chris@otree.org.
