### ISSUE TITLE
option to sort columns of export

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#433]
hi,

most of the time exported data seems to be in hunks of rounds, so that all lines from round 4 page X, say, are together.  However, at least once this was not the case for me.  It would be nice to be able to perform a sort preference (SQL `sort by`) on the data before export.  (I know this is trivial to do in `$FAVORITE_LANGUAGE`; nonetheless I think it would be a nice improvement).

Thanks,
Rasmus

**Comment by oTree-org** [comment]
Out of scope  for this release..
