### ISSUE TITLE
EditSessionProperties: changing participation_fee doesn't work

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#437]
Repro steps:
- Create a session
- Go to the "edit" tab (e.g. http://127.0.0.1:8000/EditSessionProperties/1/)
- Edit the "participation fee" or "real world currency per point", then save
- Reload the page

Note how the change is not saved. 

Code is here: https://github.com/oTree-org/otree-core/blob/922f3893faa634aee6ece12a6d0922b70fc698dd/otree/views/admin.py#L627

Note, it works if you edit "label" etc., it works -- i think this is because "participation fee" and "real world currency per point" are in the session.config (JSonField) and this field is not marked as dirty, so it is not saved...maybe related to SaveTheChange.

Need a unit test for this also.

**Comment by gregmuellegger** [comment]
I added a quite sophisticated infrastructure to support custom fields in SaveTheChange. You could add more field types in https://github.com/oTree-org/otree-core/blob/aa34f3b7c66a0ec870155d614295fda0ed0ed5af/otree/models/varsmixin.py#L58

That also makes it not necessary anymore to specialcase the `vars` field. All JSONFields are now supported.
