### ISSUE TITLE
{% formfield %} tag: Spaces around equals sign in "with" param cause error

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#438]
We should make the error more descriptive. A frequent error when setting the label:

```
C:\oTree\library [debug +5 ~1 -0 !]> otree resetdb
SystemCheckError: System check identified some issues:

ERRORS:
public_goods_simple: (otree.E008) Template syntax error in C:\oTree\library\public_goods_simple\templates\public_goods_s
imple\Contribute.html

  13 | b'        an endowment of {{ Constants.endowment }},'
  14 | b'        and an efficiency factor of {{ Constants.efficiency_factor }}.'
  15 | b'    </p>'
  16 | b''
  17 | b''
  18 | b'    {% formfield player.contribution with label = "How much will you contribute?" %}'
-----------^
  19 | b''
  20 | b'    {% next_button %}'
  21 | b''
  22 | b'{% endblock %}'

Error: 'with' in formfield tag needs at least one keyword argument.
```

**Comment by gregmuellegger** [comment]
![image](https://cloud.githubusercontent.com/assets/88278/13425351/76d45e5c-dfa6-11e5-9ea9-2a7e15f97fdc.png)

I added a more helpful message. It's only shown if we detect that there might have been a space used around the '='. The code is more precise than I was expecting, it works quite well from my perspective.

I think we could make it work that spaces around the = are allowed with not too much effort. But I'm not big fan of it as this complicates the code without gaining to much. A descriptive error message is much better than allowing people to get sloppy with their syntax.

**Comment by oTree-org** [comment]
Looks great :)
