### ISSUE TITLE
Checkbox widget doesn't look right

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#440]
Even on desktop, looks like a mobile formatted checkbox:

![image](https://cloud.githubusercontent.com/assets/5423929/13497324/176e0f28-e198-11e5-8ba1-a9da925ed64f.png)

Apparently the problem is that it has `class="form-control"`

**Comment by gregmuellegger** [comment]
I had to create a new row template for this, but it works quite well now.

Please try it out yourself, the markup is different to a normal field now. It's not contained in a `div.form-group` anymore, but in a `div.checkbox` as required by bootstrap.

Usually we had the label at the top and the field below, for checkboxes it's now first the checkbox then the label on the same horizontal height.

**Comment by gregmuellegger** [comment]
![spectacle d23244](https://cloud.githubusercontent.com/assets/88278/13670630/52dd2584-e6cb-11e5-837b-412c18b55eff.png)
