### ISSUE TITLE
If BooleanField widget is checkbox, it shouldn't be required

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#441]
In models.py:

```
my_bool = models.BooleanField(widget=widgets.CheckboxInput())
```

Resulting HTML checkbox widget has `required` attribute.

Would be better if it wasn't required by default, but if the user passed `blank=False` to the model field, it became required.

This has already been implemented by checking the name of the widget class, in the model field ``__init__``, but that technique is not robust because it doesn't consider widgets that inherit from ``CheckboxInput``.

**Comment by gregmuellegger** [comment]
I found a better solution compared to the discussed solution via a special blank property.

That is fixed now. It includes tests so that we keep the logic in place :)
