### ISSUE TITLE
Remove django-celery dependency

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#448]
According to the Celery website, django-celery is no longer required because Django support is now built directly into Celery: http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

**Comment by gregmuellegger** [comment]
Yes, this statement was already given when I integrated Celery into oTree. However it seemed the database backend for celery seemed NOT to work at that time without django-celery.

**Comment by oTree-org** [comment]
We might be able to get rid of celery if channels gets support for delaying tasks: https://github.com/andrewgodwin/channels/issues/115

So, closing this for now.
