### ISSUE TITLE
Configure session.code length

### ISSUE THREAD

**Issue by Toub** [oTree-org/otree-core#451]
Hi,

Thanks for this great project.

I would like to extend the session code from 8 to 20 characters in order to increase security, but I am new with python.

I had good results by editing otree core code (otree/models/sessions.py):

``` python
    code = models.RandomCharField(
        db_index=True,
        length=20, doc="Randomly generated unique identifier for the session.")
```

But this is a pity as I have to maintain my own version of otree.

What is the best way to deal with it?
* can I override the whole python file in otree games code (as I can do with _templates)
* should I submit a pull request to allow this size to be configured in settings.py? (and how can I do)
* ... something else?

Thanks

**Comment by Toub** [comment]
There is also an impact on database schema structure.

I am not familiar with django, but it looks like a patch /migrations/0002_extend_code_columns_length.py has to be created.

**Comment by oTree-org** [comment]
Fixed in https://github.com/oTree-org/otree-core/commit/e53699a48f64492cc38b76691e30f5f99fdfed58. Still 8 chars but now it's alphanumeric which has 2.8211099e+12 combinations.

**Comment by Toub** [comment]
Thanks, it will do the job!
