### ISSUE TITLE
howto mix bots with human players?

### ISSUE THREAD

**Issue by jpg75** [oTree-org/otree-core#461]
Hi,
I am interested in the feature of having human and bots playing together (as described in the oTree paper) for teaching or machine learning purposes. Looking at the docs, I could not find anything specific for this (testing with bots only).
Is there an out of the box manner to specify that a player must be a bot? 
For example, in the "trust" example how can I specify that player A or B must be a bot?
Thanks in advance!

**Comment by simonbusara** [comment]
Looking on how to on this. Anyone with a solution ?

**Comment by sniperdrone** [comment]
Seconding this...Right now, one can specify that the bot does nothing on a given set of pages (which a human participant could then interact with, which is 90% of what we need), however, this page is then hidden by the "bot completed" message. I think if one could disable showing that message for a specific 'sub-bot', bot/human gaming would work :)

**Comment by Subimago** [comment]
I am also interested in this feature. Did anyone find a solution or is this feature planned?

**Comment by oTree-org** [comment]
No current plans but it's on the wishlist. If you describe in more details why you want this feature, that would be useful.

**Comment by Subimago** [comment]
Right now you have the browserbots feature which is already really helpful. It would be nice if one could specify that only a subset of the players is played by these bots so that the remaining ones can be played by actual human players.

**Comment by jpmintz01** [comment]
Would also like this!  Is there a way to tell the bot in tests.py to check whether player.id_in_group == 2? 

I tried this, but player 1 where I wanted the human player (player.id_in_group == 1) still executed the bot, but did nothing, so the page hung without an input.
