### ISSUE TITLE
error mysql otree.RoomSession.room_name

### ISSUE THREAD

**Issue by PhoenixAlx** [oTree-org/otree-core#462]
Hi,
I have installed otree-core-0.5.3
and have configured of database a mysql.

When I did otree resetdb I had the next error

SystemCheckError: System check identified some issues:
                                                                                                                      
ERRORS:
otree.RoomSession.room_name: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.

The name of room session is "subsession1"

Can you help me?

Thanks

**Comment by oTree-org** [comment]
Fixed in https://github.com/oTree-org/otree-core/commit/18aa30e2e59dcd2a22482ca9e54ab8aa333a8b25, will be released to pip soon.

**Comment by oTree-org** [comment]
Can you check if it's fixed in 0.5.4?

**Comment by PhoenixAlx** [comment]
Ok, perfect ^_^
