### ISSUE TITLE
value is None after of group's function

### ISSUE THREAD

**Issue by PhoenixAlx** [oTree-org/otree-core#466]
Hi,

I have the next view:

```
class OfferEWaitPage(WaitPage):
    '''wait until offer player E'''
    def after_all_players_arrive(self):
        #we put offer to each worker offer_received and w_choosen
        self.group.set_e_offers_w()
```

In this function , set_e_offers_w(), update fields of w's players. I check results' page and it's working

After I have the next view:

```
class WAcceptOfferEPage(Page):
    '''Page where the player W Accept o reject E's offer '''
    template_name = 'wages/W_Accept_E.html'
    form_model = models.Player
    form_fields = ['w_accept_offer_e']
    def is_displayed(self):
        return self.player.role() == Constants.role_w and self.player.w_choosen == Constants.E_accept_offer_w_option;
```

self.player.w_choosen has been updated before but its value is none. 
It is strange. I am working with the last version 0.5.5 and room session with Persistent URLs

Any idea?

Thanks for your effort

**Comment by oTree-org** [comment]
Can you share your project/app with me? Or send to chris@otree.org.

Please include basic instructions of what I need to do to reproduce the error

**Comment by PhoenixAlx** [comment]
@oTree-org I have sent you a email
