### ISSUE TITLE
before_next_page(self) function without having to go to the next page

### ISSUE THREAD

**Issue by leliel12** [oTree-org/otree-core#475]
possibility in oTree to have the same functionality as the before_next_page(self) function without having to go to the next page

The issue is discussed here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/otree/tgR6CHFwSSE/OP7JYLulBAAJ 

We can use the #469 (ajax method) or in other case we can make something different

**Comment by leliel12** [comment]
@oTree-org @gregmuellegger we need some discussion here

**Comment by solstice** [comment]
+

**Comment by gregmuellegger** [comment]
@leliel12 Sorry, I lack the knowledge about the context at the moment. And I don't have much time-resources to dive into this anytime soon.

**Comment by oTree-org** [comment]
Use Django channels: http://otree.readthedocs.io/en/latest/misc/django.html#real-time-and-websockets
