### ISSUE TITLE
custom page_name

### ISSUE THREAD

**Issue by JKRhb** [oTree-org/otree-core#476]
Dear oTree-team,

I'm using multiple instances of the same page whose values/formfields are altered everytime it is displayed. This works quite well, however, as I want to be able to use the "time spent on each page" feature properly, it would be nice if the `page_name` was changeable and (more) independent from the page's class name. (I tried changing the value of `self.__class__.__name__` in the `before_next_page` method but this seems not to be a good idea.) Could this be added or might it already possible to achieve in the current oTree-version?

Thanks in advance!

Jan

**Comment by oTree-org** [comment]
Don't know if this will work specifically in your case, but you could split it into several pages, and use class inheritance so you're not repeating the code: http://otree.readthedocs.io/en/latest/tips_and_tricks.html#views-py-prevent-code-duplication-by-using-inheritance

**Comment by JKRhb** [comment]
Thank you, this goes into the right direction! I must have overlooked it when I searched the docs for a solution. I wondered, though, if there is a way to create the classes derived from the BaseClass dynamically or if you have to create page1, page2, ... pageN manually.

**Comment by JKRhb** [comment]
Hmm, I just realized that it isn't possible to change the `page_sequence` on the player or participant but only on the global level. The questions I have are displayed randomly for each participant and it would be nice to track their order of appearance. Could you maybe add a string variable like `page_name` to the `Page` class that is set to self.__class__.__name__ by default but can also be changed (dynamically)? That would absolutely great!
