### ISSUE TITLE
Set USE_POINTS per app?

### ISSUE THREAD

**Issue by alightner** [oTree-org/otree-core#481]
Hi, I am running an experiment using multiple separate games that will use either points (with custom name) or USD. Currently, it seems that we can only set this in the settings.py file, which applies to all games. It would be convenient to set it e.g., in the Constants class. Is there any way to do something like this? Thanks.

**Comment by oTree-org** [comment]
USE_POINTS is a global setting; I found it would be complicated to do it per-app or per-config, because then the `c()` function would need to be aware of the app or config it's in.

**Comment by grasshoppermouse** [comment]
Many thanks for the response. Any ideas for a workaround? (I'm working with alightner).

**Comment by oTree-org** [comment]
I recommend either making your own currency using FloatField or IntegerField, or putting them in separate projects..
