### ISSUE TITLE
Channels hanging if message not properly formatted -- documentation issue.

### ISSUE THREAD

**Issue by mbirkegaard** [oTree-org/otree-core#488]
http://otree.readthedocs.io/en/latest/django.html#real-time-and-websockets doesn't specify the format of websocket messages, but the example uses `message.reply_channel.send({"accept": True})`. However, sending this message causes the server to hang. No message is seen client-side, and refreshing the page eventually returns a 503 from Daphne. 

To avoid the server hanging, messages can only have the top-level key "text", i.e. `message.reply_channel.send({"text": ...})` (and not `message.reply_channel.send({"text": ..., "any_other_key": ...})` for instance).

**Comment by oTree-org** [comment]
Yes you are right, that example is for channels>=1.0 (I pasted it from the channels docs), but oTree is still on v0.17.3. I will decide what to do about this.

**Comment by oTree-org** [comment]
I added a note to the docs, which I will remove when I upgrade channels to v1. http://otree.readthedocs.io/en/latest/django.html#real-time-and-websockets
