### ISSUE TITLE
view.has_timeout() is False when using only get_timeout_seconds

### ISSUE THREAD

**Issue by nwself** [oTree-org/otree-core#490]
Steps to reproduce
1. `otree resetdb` (seems important)
1. Go to a view that (a) has `get_timeout_seconds` defined, (b) does __not__ have `timeout_seconds` defined and (c) has a template that inherits from `Page.html`

I expect to see the `#otree-timeout` banner. I do not.

It seems that `Page.html` does not show the timeout banner because view.has_timeout() returns False here. __Is this expected behavior?__ The docs don't say.

Workaround: override `has_timeout()` on the view and just return True. (This seems to work but potentially might conflict with whatever `PageTimeout` is doing?)

**Comment by nwself** [comment]
I should have said that I just upgraded to 1.3.9.

Also, I've learned some more things about this problem. Actually, `get_timeout_seconds` does work after refresh, like so:

1. Go to a view with `get_timeout_seconds`, without `timeout_seconds`, and with a template that inherits from `Page.html`
1. There is no timeout banner
1. Refresh the page
1. Now there is a timeout banner

In fact, the same thing happens for views with `timeout_seconds` defined and without `get_timeout_seconds`. There is no banner on initial page load but it shows up after refresh.

**Comment by oTree-org** [comment]
> It seems that Page.html does not show the timeout banner because view.has_timeout() returns False

It sounds like you are still on an old version of otree-core. oTree no longer uses view.has_timeout to decide whether to show that banner. view.has_timeout is just an internal function, not part of our public API. Where do you see this?

**Comment by oTree-org** [comment]
Is this your code?

https://github.com/NGS2Montage/montage-otree/blob/master/_templates/global/Page.html

(I saw you are committing in this repo)

It looks you pasted the internal otree-core Page.html into your project and made modifications there directly. That references a bunch of internals, so it will break when you upgrade.

**Comment by oTree-org** [comment]
global/Page.html should look like this: https://github.com/oTree-org/oTree/blob/master/_templates/global/Page.html

**Comment by nwself** [comment]
Oof. You are absolutely correct and a good detective. We have no business checking in that template like that. Thanks so much for all the work!
