### ISSUE TITLE
export error when using ForeignKey in Player, Group

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#493]
The usage of ForeignKey in models brings in error when exporting the data via admin interface.
It is result of the fact that the actual field name has an '_id' suffix for ForeignKeys. So if the field is named 'foo', it is stored as 'foo_id', so when in export.py  it tries to reach 'foo' it raises the error.

It could be resolved by using the option 'db_column' when ForeignKey is declared but for some reasons it doesn't work (I haven't figured yet why).

(Reported by Philipp)

**Comment by bjgoode** [comment]
We have the same problem in our project. This is our solution forked from otree-core: https://github.com/bjgoode/otree-core/commit/ab6bbcbdb53cb1d74b205f04f16eb40ea099a45d
