### ISSUE TITLE
Somtimes waiting 

### ISSUE THREAD

**Issue by z0nam** [oTree-org/otree-core#494]
oTree 1.4.11

I conducted a oTree session with 62 students with 8 subsessions (or rounds), and I found that some students stuck at waiting page (about 10 times and various devices). Refresh page worked.  It seems that this could happen when students use mobile devices. The other students with their own laptop computer did not experience this issue.

**Comment by oTree-org** [comment]
Hi, thanks for reporting. I know about this issue and I just released a fix.
