### ISSUE TITLE
get chat contents in models.py

### ISSUE THREAD

**Issue by myuuuuun** [oTree-org/otree-core#502]
Hi. I'm planning to make a two player repeated game experiment with communication, in which

1. Communication round: first plyaers communicate with each other via `chat`
2. Repeated game rounds: play a t-period repeated game

I'd like to show to players the content of the past chat in the repeated game rounds. Is there an official way to get the contents of the chat in `models.py`?

**Comment by oTree-org** [comment]
This is not supported. Though if you have knowledge of Django you might be able to query messages through the ORM. Although this is an internal schema that may break in the future.

**Comment by myuuuuun** [comment]
Okay, I see. Thank you!
