### ISSUE TITLE
Access `session.config` in `Constants`

### ISSUE THREAD

**Issue by myuuuuun** [oTree-org/otree-core#503]
Hi! [Tips and tricks](https://otree.readthedocs.io/en/latest/misc/tips_and_tricks.html?highlight=session.config) page in the documentation has a following description: 

> If you need multiple rounds, set num_rounds. If you need slightly different versions (e.g. different treatments), then you should use the techniques described in Treatments, such as making 2 session configs that have a different 'treatment' parameter, and then checking for self.session.config['treatment'] in your app’s code.

Now I'd like to ask: Is there a way to write the value of `num_rounds` in `settings.py` and refer to it in the definition of `class Constants`?

**Comment by oTree-org** [comment]
No, see here in documentation:

Variable number of rounds

If you want a variable number of rounds, consider setting num_rounds to some high number, and then in your app, conditionally hide the {% next_button %} element, so that the user cannot proceed to the next page.
