### ISSUE TITLE
How to use Chinese in html

### ISSUE THREAD

**Issue by wfc1994** [oTree-org/otree-core#504]
When modifying html, use Chinese, cmd prompts me to convert the page to utf-8
![image](https://user-images.githubusercontent.com/26211896/46728222-e2707300-ccb4-11e8-807b-65588b9d7d42.png)
However, after saving it as utf-8, I still got an error.
![image](https://user-images.githubusercontent.com/26211896/46728344-2d8a8600-ccb5-11e8-85fa-786e0daea2c0.png)

**Comment by oTree-org** [comment]
Chinese works fine for me. I think the problem you are experiencing is a different issue. All content must be inside a block. For example:

```
{% block title %}
    Text can go here
{% endblock %}

But no text allowed here!

{% block content %}
   Text can go here
{% endblock %}

No text alllowed here!
```
Make sure you don't have any content outside a block. It might be that "square" character in the screenshot.
