### ISSUE TITLE
Python won't open otree

### ISSUE THREAD

**Issue by JanaJarecki** [oTree-org/otree-core#515]
I have installed python and otree and need to start the server 8001 (because we don't have access to 8000 from my university).

However, this does not work with the following error
    
    > otree runserver 8001
    c: ...\python\python37\python.exe: can't open file 'C:...\Python\Python37\Scripts\otree':
    [Errno 2] No such file or directory

In my Python37\Scripts directory the following files do exist

- otree.exe
- otree-script.py

Is this a (known) bug or an error on my side?

Specs:
Windows 10
Python 3.7
otree-2.5.5

**Comment by JanaJarecki** [comment]
Sorted. I found out that the `runserver` command has been depreciated and now only the `devserver` command exists, that means this works:

    otree devserver 8001

Maybe a friendly warning about the "runserver" command being depreciated may help users?

**Comment by oTree-org** [comment]
Hi, thank you for reporting. Yes runserver has been removed. Although it seems oTree is giving a confusing error message about that. I'll investigate and fix, thanks.

**Comment by oTree-org** [comment]
Fixed locally.
