### ISSUE TITLE
Is possible to modify `page_sequence` for created sessions?

### ISSUE THREAD

**Issue by weilu** [oTree-org/otree-core#533]
I deployed an experiment with multiple rounds for an app, but after the 1st round we realized that we need to add some pages to `page_sequence` and reorder some of the existing pages. Is this possible within the framework of otree? If so how? If not, any suggestions on what's the best way to approach this? like manually creating new sessions with the updated `page_sequence` and porting existing users over?

**Comment by oTree-org** [comment]
Adding pages to a session is not supported. You will need to create a new session.

**Comment by oTree-org** [comment]
Not sure about porting users to a new session; I have never done that and I don't think it will be straightforward.
