### ISSUE TITLE
MS SQL Server support

### ISSUE THREAD

**Issue by HLiuUS** [oTree-org/otree-core#536]
oTree currently limits the database for production to Postgresql and MySQL, it is probably a good idea to support MS SQL Server considering its usage across schools and enterprise.

**Comment by oTree-org** [comment]
Thank you for the feature request. I will put it on my list of things to consider for the future. Though I may not get to it soon. It may not be complicated to modify the code to support SQL Server. However, the main issue is the commitment to continuously test & support SQL Server.
