### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by csemken** [oTree-org/otree-core#539]
Currently, https://otree.readthedocs.io/ only documents the latest version of otree.  However, there may be good reasons to use old versions.  For example, the [otree_tools](https://github.com/chapkovski/otree_tools) extension does not work with recent versions of otree.

I therefore suggest to provide a versioned documentation for otree.  Readthedocs has a [guide](https://docs.readthedocs.io/en/stable/versions.html) on how to set this up, including through git tags.

**Comment by oTree-org** [comment]
Hi, if you want to get the docs for an old version, here is the repo with the full history: https://github.com/oTree-org/otree-docs. Find a commit from the time your oTree version was current and browse that. Other than that, I need to focus on the current release and encourage people to stay up to date. By the way I'm wondering what features of otree_tools you rely on?

**Comment by csemken** [comment]
Ok thanks for the help @oTree-org.  I will close the issue then.  

> By the way I'm wondering what features of otree_tools you rely on?
I am using one of the input methods: AdvancedSliderWidget.  I have been able to isolate the code for this now, so I can use it in oTree 3 without having to import any of the incompatible features.
