### ISSUE TITLE
Please allow a way to load/identify room-specific data/info

### ISSUE THREAD

**Issue by toobaz** [oTree-org/otree-core#541]
My experiment's participants are deterministically matched among them. This matching is fixed ex ante but differs from room to room.

For instance, for my room ``r1``, I have a file ``r1_data.py`` containing something like:
```python
{'abc' : 'group1', 'def' : 'group2', 'ghi' : 'group1'}
```
... where ``'abc'``, ``'def'``, and ``'ghi'`` are labels found in room ``r1``'s ``participant_label_file``.

Unfortunately, I found no way to tell oTree to load ``r1_data.py`` (rather than, say, ``r2_data.py``).

Or more precisely: I have found only one way, and it is horrible. What I currently do is to open all files in a given directory containing ``r1_data.py``, ``r2_data.py``... until I found one containing a label which is among the labels in the current session (as labels are unique across rooms).

There would be an easy fix to this, which would be to let my code know which room it is running in (if any). Unfortunately I couldn't find this information neither in ``self.session.__dict__``, nor in ``self.player.participant.__dict__``.

**Comment by toobaz** [comment]
(Sure, there's another way: encode somehow the room number inside each of the room's labels... but if the content of ``participant_label_file`` is meant to be more than mere individual identifiers, maybe this could directly be a csv?)

**Comment by oTree-org** [comment]
Hello, thank you for the suggestion. There is no public API for getting the current room, but you can access the current session config. So you can add custom key that identifies the room:

```python
SESSION_CONFIGS = [
    dict(
        name='my_session',
        display_name="My Session (fill in the room_number key)",
        room_name="1",
        num_demo_participants=3,
        app_sequence=['public_goods'],
    ),
]
```

When you create a session, click the "configure session" as described here: https://otree.readthedocs.io/en/latest/treatments.html#configure-sessions

And enter the name/number of the room you are creating the session in.

Your code can access the current room name, and pre-assign participants to labels:

```
class Subsession(BaseSubsession):

    def creating_session(self):
        from pathlib import Path
        room_name = self.session.config.get('room_name')
        if room_name:
            labels = Path('_rooms/{}.txt'.format(room_name)).read_text('utf-8').splitlines()
            for i, player in enumerate(self.get_players()):
                player.participant.label = labels[i]
```

This technique is described here: https://otree.readthedocs.io/en/latest/rooms.html#pre-assigning-participants-to-labels

Does that help?

**Comment by toobaz** [comment]
> Does that help?

It does in principle solve my problem, yes. But if I understand correctly, it breaks the abstraction between rooms and sessions. In my case, I have a single session type (=config) which I want to run on multiple different rooms. Since you are suggesting to hardcode the ``room_name`` into the session config, this means I should change the session config everytime I change a room - or create a different session config for each session-room combination. So I'll rather stick to my hack of encoding the room number inside the participant labels.

(Please let me know if there is something I misunderstood)

**Comment by oTree-org** [comment]
You don't have to modify the session config in the source code, or have multiple session configs. You just set it once, then whenever you create a session, you set the room name in the admin, as shown in the screenshot here: https://otree.readthedocs.io/en/latest/treatments.html#configure-sessions

**Comment by toobaz** [comment]
OK, now I see. Indeed, I had missed that custom fields in the settings are automatically exposed in the interface.

Thank you very much, this is indeed a solution to my problem.

(Not sure it's a solution I'll adopt, to be honest - it's something I or my collaborators would be likely to forget when starting an experimental session, as opposed to anything which is set in the code. But I understand APIs are partly a matter of preferences.)

**Comment by oTree-org** [comment]
OK sure. If you opt to use it, you can set the default to some invalid value and throw an exception in creating_session if the experimenter forgot to change it from the default.

Anyway thank you for the feedback.
