### ISSUE TITLE
GitHub repository lags PyPI, missing recent releases

### ISSUE THREAD

**Issue by peterjc** [oTree-org/otree-core#542]
The https://github.com/oTree-org/otree-core/commits/master commit history gives the clear impression is that the real development happens elsewhere, and only periodically does this copy get updated.

Currently https://github.com/oTree-org/otree-core/blob/master/otree/__init__.py says version 3.0.1, last updated 7 July 2020, shortly after the v3.0.1 release on PyPI: https://pypi.org/project/otree/#history

Since then, PyPI has releases 3.0.2, ..., 3.0.12 (October 2020), but apparently they have not been shared here on GitHub.

Could you update this repository please?

**Comment by FlorianFranzen** [comment]
I would like to second that. For example I added [worker support](https://channels.readthedocs.io/en/stable/topics/worker.html) for extensions, but the way development is currently performed, it is difficult to contribute this upstream.

**Comment by bbo2adwuff** [comment]
If you customize some parts and they fail after you upgrade, it would be useful to be able to just browse through the last commits to what changed.

I downloaded the tar files of two versions from https://pypi.org/project/otree/ and then I used `diff` to see what changed...

@oTree-org Is there a reason why you don't commit to this repo?

**Comment by peterjc** [comment]
Getting off topic, but years ago I wrote https://github.com/peterjc/tarball2git for turning a series of version named tar-balls into a linear history git repository exactly for tracking changes. The original use case was for a tool pre-dating git, but the core problem was the same.

**Comment by peterjc** [comment]
Still no sign of any recent releases here on GitHub :cry:

I understand you are now working on v5 oTree Lite, so you might have to have multiple branches here for that and the older v3 code which is already up to v3.4.0

**Comment by peterjc** [comment]
I see https://github.com/oTree-org/otree-core/blob/master/otree/__init__.py now has 5.0.0a1 released Jan 2021, but is again out of date.

It would also really help if as part of pushing a release to this repository, you could also resume using git tags please.

**Comment by peterjc** [comment]
On the Google Group Chris wrote:

> ... Adding new features to otree-core is already really challenging and I don't want to change the workflow I have now. However, if someone wants to make a script that makes git diffs out of the releases on PyPI from here then I would be happy to host that repo on the official oTree GitHub account, so that people can browse the difference between releases. ...

and:

> This URL provides all oTree releases in JSON format: https://pypi.org/pypi/otree/json
It has links to the tarballs.

I intend to have a look at this, and hope to prepare a pull request for the v5 changes not yet here on the master branch.

**Comment by peterjc** [comment]
I got distracted and did not make that pull request, but note the otree-core on this GitHub repo has not changed since [13 Dec 2020](https://github.com/oTree-org/otree-core/commit/02fe27fbfa1d58ddfe7ba4f6ed6177bad29f94c8)
