### ISSUE TITLE
How to customize participant label entry page?

### ISSUE THREAD

**Issue by weilu** [oTree-org/otree-core#545]
Currently the page says:
```
Welcome
Please enter your participant label.

```

I'd like to change it to something else – participant label isn't very meaningful in the context of our experiment. I want to change it to student ID for example. Is there a way to achieve this?

**Comment by weilu** [comment]
Also, when an invalid label is entered the error message says "Invalid entry; try again.". Can this be changed?

**Comment by oTree-org** [comment]
Sorry, customization of this page is not currently supported.

**Comment by weilu** [comment]
Here's a workaround I found:
Since my study is in Spanish, I can effectively change the translation and that gets me 90% there - baring the css difference of the page.
I copied https://github.com/oTree-org/otree-core/blob/a01b6bfcc3020b70e14cf299830ec9a9b485a057/otree/locale/es/LC_MESSAGES/django.po to `locale/es/LC_MESSAGES/django.po` under my project folder, changed the translations for "Welcome", "Please enter your participant label." and "Invalid entry; try again." then ran `django-admin compilemessages` to generate the django.mo file. 

So this is one way to do it.
