### ISSUE TITLE
"Waiting for" participants that are not lagging behind

### ISSUE THREAD

**Issue by toobaz** [oTree-org/otree-core#547]
In an experiment we are running, it frequently happens to see in the "monitoring" page:
- participants who are stuck on a waiting page but have no other participants left behind them
- participants who are "waiting for" other participants who are actually preceding them

I *think* the first problem is related to participants temporarily losing Internet connection - I still mention it in case it's related to the second.

The second, however, is just puzzling.

In both cases, the problem persists until we "Advance slowest user(s)", and is solved then.

All of this is happening under Otree 3.0.6 (and I couldn't find a changelog to check for any related change since 3.3.6 - fixing #542 would help). So while this is not the last version, it's definitely more recent than the 0.3.3 mentioned in #354 - the only related issue I found.

I'm attaching a screenshot. While unfortunately the top of the page is missing, those participants were all at page 46 or 47.
![Monitor_screenshot](https://user-images.githubusercontent.com/1224492/101504311-5aa95080-3973-11eb-9a80-05db7e89990a.png)

**Comment by oTree-org** [comment]
Are you running multiple dynos? That could cause this.

**Comment by oTree-org** [comment]
(I happen to be in the middle of a major new release. I have refactored wait pages, so hopefully if there is a bug here, it will get fixed with the new release.)

**Comment by toobaz** [comment]
I'm using a single dyno on `runprodserver1of2`. I don't think it's relevant, but just in case: I'm using the "Hobby Dev" Redis package.

**Comment by oTree-org** [comment]
Hi, I have released an alternative implementation of oTree that is simpler in how it handles wait pages. How about trying it out to see if it solves this issue? Details are here: https://otree.readthedocs.io/en/latest/misc/otreelite.html

You could also try oTree 3.3.x if you cannot use that alternative version.

**Comment by toobaz** [comment]
> You could also try oTree 3.3.x if you cannot use that alternative version.

Seems like the "alternative version" is the only supported one in the reasonable future, as the page you linked "_I will be actively maintaining both_"... but new version numbers are use for the "lite" version? So I guess I'll have to give it a try. But that probably won't be on the current experiment, as it would require several fixes to the code (it uses Django templating extensively). So closing for now, as the bug affects an old version.
