### ISSUE TITLE
Please support python 3.9

### ISSUE THREAD

**Issue by toobaz** [oTree-org/otree-core#549]
Python 3.9 was released in December 2020 and is becoming the default (e.g. in Ubuntu/Debian), but ``pip`` fails to install otree stating ``This version of oTree is not compatible with Python 3.9.``.

Maybe there is no real incompatibility and some requirements file just requires an update?

**Comment by oTree-org** [comment]
oTree Lite works on Python 3.9:

pip3 install -U "otree>=5a"

**Comment by toobaz** [comment]
Thank you for the pointer. However, given that the code for the experiment I'm working on was tested with standard otree (and that at least temporarily I can force python 3.7 as interpreter), I would rather wait for standard otree to support 3.9, if it's planned.

**Comment by toobaz** [comment]
By the way: it's just my opinion, but I would find it less confusing if otree-lite was distributed in pypi with its own name/project rather than as a set of "pre-release" otree-core versions. In particular given than an [actual release](https://groups.google.com/g/otree/c/aUFu1bz5U8Q) is approaching.

**Comment by oTree-org** [comment]
Sorry, but I don't have resources to test and support Python 3.9 on oTree 3.x. I suggest using the same version of Python that you originally developed your experiment on.

**Comment by oTree-org** [comment]
> By the way: it's just my opinion, but I would find it less confusing if otree-lite was distributed in pypi with its own name/project rather than as a set of "pre-release" otree versions. In particular given than an [actual release](https://groups.google.com/g/otree/c/aUFu1bz5U8Q) is approaching.

Thank you for the feedback but I don't want to split it into 2 packages. Many people would end up with both packages installed side by side, and then get confused about which version is installed, "import otree" would behave unpredictably, etc.

**Comment by toobaz** [comment]
> Sorry, but I don't have resources to test and support Python 3.9 on oTree 3.x.

So oTree 3.x will sooner or later be abandoned? It's clearly your right to do so, I had just understood there were different plans.

**Comment by oTree-org** [comment]
No, it's not abandoned, I am just not supporting Python 3.9 on it.

**Comment by toobaz** [comment]
> No, it's not abandoned, I am just not supporting Python 3.9 on it.

Python 3.8 support is planned until approximately October 2024. That's quite a bit of time, but still, if the standard oTree will become abandonware at that time, it's enough to more seriously consider switching to otree-lite before investing more in django-specific techniques.

I would find it perfectly natural after the "brain transplant" to give people a reasonable amount of time to switch, and then pull the plug to the old oTree. But stating you will continue to support it and at the same time that you won't support new Python versions is... well, I don't understand it.
