### ISSUE TITLE
Rest Api: Get params not parsed

### ISSUE THREAD

**Issue by MPW1412** [oTree-org/otree-core#550]
Hello,

the sources here don't seem up to date. Based on the sources pip installs, in `otree/views/cbv.py` in case of a get call, parameters aren't parsed and call for `/api/session` is not possible:

```
get() missing 1 required positional argument: 'code'
```
(included for search engines^^)

To fix this, make the following changes in lines 181 following. 

Old:
```
        if body:
            payload = json.loads(body)
        else:
            payload = {}
```
New:
```
        if body:
            payload = json.loads(body)
        elif request.method == 'GET':
            payload = {}
            for paramset in str(request.query_params).split('&'):
                key, value = paramset.split('=')
                payload[key] = value

        else:
            payload = {}
```

There might be more elegant ways to parse the parameters. I didn't find an easy way in starlette and I didn't know what other dependencies you might want to bring in. So this is a pure regex approach.

Best,
Matthias

**Comment by oTree-org** [comment]
Hi, you are supposed to pass the parameters as JSON, not querystring. See the examples here: https://otree.readthedocs.io/en/latest/misc/rest_api.html#setup

**Comment by MPW1412** [comment]
@oTree-org, to my understanding, that violates RFC2616. Bodys in GET-Requests should be ignored. You should make it a POST-Call then.

**Comment by MPW1412** [comment]
@oTree-org, a colleague of mine just discovered, that the fetch API, which is probably one of the most important http client implementations, doesn't even support that:

```
fetch("/api/session/", { 
                    headers: {'Accept': 'application/json', 'Content-Type': 'application/json'}, 
                    method: 'GET',
                    body: JSON.stringify({code: 'bxaazvbw'})
                }
            )
        .then(res => console.log(res))
        .catch(res => console.log(res))
TypeError: Window.fetch: HEAD or ### GET Request cannot have a body.
```

**Comment by oTree-org** [comment]
Hm, I see, I guess you are right. OK I should be able to fix that soon, thanks for reporting.

**Comment by oTree-org** [comment]
This endpoint is fixed in the latest 5.x release. See updated docs here: https://otree.readthedocs.io/en/latest/misc/rest_api.html
/api/session renamed to /api/sessions/ also.

Thank you!
