### ISSUE TITLE
Nonnull check catching null model properties

### ISSUE THREAD

**Issue by gramorgan** [oTree-org/otree-core#552]
I'm on oTree 5.7.1 and Python 3.9

I'd like to be able to create nullable fields on my models which just return None when the field is null. It's sometimes a little annoying to have to wrap every potentially-null field access in a try, so I thought I'd wrap my nullable fields in a property:

```python3
class Player(BasePlayer):
    _my_field = models.IntegerField(initial=None)

    @property
    def my_field(self):
        try:
            return self._my_field
        except TypeError:
            return None

    @my_field.setter
    def my_field(self, value):
        self._my_field = value
```

The issue is that this still doesn't work since the nonnull check in `__getattribute__` for the model base class doesn't differentiate between db field attributes and properties. So this still fails the nonnull check and throws a TypeError when the property is accessed.

Not sure if anyone else cares about this but it seems like it might be a bug so I thought I'd open an issue for it.
Thanks!

**Comment by oTree-org** [comment]
There are several ways of dealing with this. One is define a function like:

```
def get_nullable(obj, field_name):
    try:
        return getattr(obj, field_name):
    except TypeError:
        return None
```

Another is to set the field's initial value to 0 or -1 etc and use that as the sentinel value.
