### ISSUE TITLE
Feature request: specify whom to wait for waiting pages

### ISSUE THREAD

**Issue by qwiglydee** [oTree-org/otree-core#558]
Use case, abstracted:
- game simulates environment with different roles: Workers (few players) and Boss (one player)
- the Workers do not interact with each other, they play independently
- the Boss interacts with Workers
- Workers and Boss have different page sequences of different length and duration

At some points of workflows, Boss should wait for Workers or Workers should wait for Boss,
but Workers do not need to wait for each other.

It would be nice, if we could specify whom to wait at `WaitPage`s, in a way analogous to `is_displayed`.

**Comment by oTree-org** [comment]
You can use `is_displayed` on waitpages as well. It works the same way as a regular page. If is_displayed is False, the player skips past and doesn't need to wait. The waitpage proceeds once all players have arrived (or skipped past).

If you want more complex logic, you can use live pages: https://otree.readthedocs.io/en/latest/live.html
You can make it do anything, keep certain users on the page until some condition is met.
