### ISSUE TITLE
Data monitoring swaps values across players on Heroku

### ISSUE THREAD

**Issue by toobaz** [oTree-org/otree-core#559]
I have an experiment in which the data shown inside the monitoring web interface very often does not match the actual code, nor downloaded data.

Here is an example:

![Weird data](https://user-images.githubusercontent.com/1224492/121722800-10518980-cae6-11eb-9bec-2ef7ac518dfd.gif)

Notice that P2 has `id_in_group=2` (in the debug info, but also in the page and in the data when downloaded as csv), but in the `Data` view, it has `id_in_group=3`.

This actually happens for various variables (all?), not just the ones related to group.

This happens with multiple oTree versions (tested 5.1.4, 5.2.0, 5.2.2), but I was only able to reproduce on Heroku. My local sessions with `otree devserver` work just fine.

I will try to produce a minimal working example but it's gonna be tedious - since I can't test locally. If @oTree-org you have any hint of what could be causing this, it might help a lot.

**Comment by toobaz** [comment]
Something I did not mention (except in the title) is that values are not just wrong, but they are swapped across participants; and that the swapping is not the same across variables.

In case that helps: Heroku is using one "Standard 1X" dyno (providing one also for `runprodserver2of2` does not make a difference), stack is `heroku-18`, Python version is 3.8.10.

**Comment by oTree-org** [comment]
Hi, thanks for the report. I will take a look at this later, but for now try doing a full refresh (Ctrl+F5) in your browser to clear any old cached javascript files.

**Comment by toobaz** [comment]
> try doing a full refresh (Ctrl+F5) in your browser to clear any old cached javascript files.

I tried, no change. In fact the switching mapping seems to be perfectly consistent across devices and browsers, including in incognito mode. Notice that it differs instead from round to round (there are also variables which are fine in some rounds and swapped in others).

**Comment by oTree-org** [comment]
Can you share a link to the server so I can see for myself? You can email the link to chris@otree.org.

**Comment by toobaz** [comment]
> Can you share a link to the server so I can see for myself?

Done. Here instead you can find minimal code to reproduce:

https://gitlab.com/pbat/ucdebug/-/tree/master/

It seems like the bug actually disappears if I replace the body of `creating_session` in https://gitlab.com/pbat/ucdebug/-/blob/master/ucpub/models.py with `pass`.

But the bug is in no way related to the specific method adopted to build groups - in my original app, groups were created randomly and then kept fixed across rounds.

**Comment by toobaz** [comment]
> stack is `heroku-18`

Also happens with `heroku-20`

**Comment by oTree-org** [comment]
I now see the bug and fixed it in the latest release. The query that retrieved the players for the data tab was missing an order_by clause. On postgres, this caused them to sometimes be retrieved in the wrong order. Fixed in 5.2.3, let me know if you see it again.

Thank you for the detailed report and repro code.

**Comment by toobaz** [comment]
Thanks! I can confirm 5.2.3 works fine.
