### ISSUE TITLE
Session monitor forces participants to go to next app

### ISSUE THREAD

**Issue by bjoernbos** [oTree-org/otree-core#560]
I am experiencing some updating behavior of the session monitor which I wouldn't expect.

Let me give you some background: I have an experiment in which some participants are excluded if they fail some attention checks. To inform them about their exclusion, I added a so-called `fail` app at the end of the experiment to which they are forwarded (i.e., `app_sequence=['intro', …, 'survey', 'fail']`). Participants that succeed the attention checks should end with a `survey` app.

To monitor how many participants are excluded, I am relying on the session monitor.  When I do not refresh the session monitor page, it shows (correctly) that I once failed an attention check and ended with the fail app, and that I once succeeded these checks and ended with the survey app:

![Bildschirmfoto 2021-07-13 um 12 52 52](https://user-images.githubusercontent.com/32138245/125441529-336d200e-d9e7-4512-abdc-5199d5245369.png)

However, if I refresh the session monitor it somehow forwards the second player to the fail app, although he never reached that.

![Bildschirmfoto 2021-07-13 um 12 53 11](https://user-images.githubusercontent.com/32138245/125441637-074e2047-3ba6-4148-9817-2566d9b8df0b.png)

I would have expected that the second participants stays in the survey app such that I can see how many have been exluded due to inattention here. Note that I set in the survey app that participants should not be forwarded to the fail app.

```
class P20_Thank_You(Page):

    def app_after_this_page(self, upcoming_apps):
        return upcoming_apps[0]
```

**Comment by oTree-org** [comment]
Thanks for reporting, can you show the server logs from when this happens? That would help me understand and debug it.

**Comment by bjoernbos** [comment]
I'm afraid the server logs are not very informative here. I have created a reproducible example here: https://github.com/bjoernbos/otree_bug_example. My hunch is that the function…

```
def app_after_this_page(self, upcoming_apps):
        return upcoming_apps[0]
```

… is not working properly when the upcoming app is the final one.

**Comment by oTree-org** [comment]
Hi, thank you for the repro case, but I can't reproduce this issue. Can you tell me the specific steps to reproduce this issue? Especially since the page names in the sample app don't match the ones in your original bug report & screenshots.

**Comment by bjoernbos** [comment]
Of course, please find below a screencast which reproduces the necessary steps:

- You open two tabs for two participants and monitor their progress in a third tab.
- Participant 1 succeeds the attention check and finishes after the survey on page `SurveyThanks`. 
- Participant 2 fails at the attention check and ends on page `Exclusion_Info`.
- Until then, both are correctly displayed on the SessionMonitor. But if I then refresh the SessionMonitor in the end, Participant 1 is forced to the Page `Exclusion_Info` which he never saw.

<br>
 
![output](https://user-images.githubusercontent.com/32138245/128142516-cdeab13a-e004-44ed-8b2c-9adc708fbfe9.gif)

**Comment by oTree-org** [comment]
Thank you for the video. The "no more pages to show" page should not normally be seen, because you should not have a "next" button on the last page. (It's basically an error message / warning). Does this issue still reproduce if you remove the button from the last page?

**Comment by bjoernbos** [comment]
Alright, this is a very good know! I have not been aware that one should not have a "next" button on the last page. Without that button, this issue is solved.
