### ISSUE TITLE
issue with "cheating" while testing live pages  

### ISSUE THREAD

**Issue by qwiglydee** [oTree-org/otree-core#562]
The `call_live_method` doesn't have access to current bot player.
That prevents testing code to look up some internal data and "to cheat" in order to provide predictable answers.

In case of anti-cheating implementations like the captcha it becomes totally impossible to generate predictable input from bots.
The workaround is to setup special testing session and adjust main code to generate predictable puzzles (this effectively excludes normal code from testing though).

I believe it makes sense to add player to the kwargs of the  `call_live_method`

**Comment by oTree-org** [comment]
Good point, I will take a look at doing this.

**Comment by oTree-org** [comment]
I have added 'group' as a kwarg to call_live_method in the latest release (this is a provisional/beta change).
Thanks for the suggestion!

**Comment by qwiglydee** [comment]
I'm a bit confused about what repository is currently official otree
source?

The otree-core hasn't been updated since past year.
