### ISSUE TITLE
GUI enhancement - improve icons on monitor page

### ISSUE THREAD

**Issue by peterjc** [oTree-org/otree-core#567]
The monitor page has two sets of icons bottom left - for selecting the app, and selecting the round:

<img width="184" alt="Screenshot 2021-08-11 at 09 09 37" src="https://user-images.githubusercontent.com/63959/128993935-e763393d-a24f-4b87-a252-58a5b0789726.png">

The icons have no tool tips, I would suggest "Previous Round", "Next Round", and "Reload Road".

Also the previous and next icons are identical. I initially took them to mean "Round 1" and "Round 2", especially since they have that behaviour when there are only 1 or 2 apps or rounds.

Adding or replacing a left/right arrow would clear this up, something like this perhaps?

<img width="184" alt="Screenshot 2021-08-11 at 09 09 37" src="https://user-images.githubusercontent.com/63959/128994782-cba30b0c-3605-4fde-8437-851d6cf8a8b9.png">

**Comment by oTree-org** [comment]
Thank you for reporting; it turns out these are unicode characters that don't render on some OSes, hence why you see the lines. I have fixed it locally and it will be in the next release, thanks!

**Comment by peterjc** [comment]
Huh - I wouldn't have guessed. It sounds like you've reproduced it, but this was macOS on Google Chrome.
