### ISSUE TITLE
Multiple players with the same role are not properly supported in groups

### ISSUE THREAD

**Issue by somas95** [oTree-org/otree-core#571]
By default oTree assigns a role to each player in a group, but it is not really supported to assign the same role to more than one player in the same group. Of course this is python and you can just do `player._role = Constants.role`, but that's not ideal and methods such as `get_player_by_role` won't properly function with that approach.

It is not strange to have more than one people with the same role per group (for example, you could have one seller and n>1 bidders), so it'd be great to have this functionality.

We could do the work and upstream it, but it seems like this repo lags behind pypi releases (see #542 ). What's the status on that?

**Comment by oTree-org** [comment]
Hi, see here: https://github.com/oTree-org/otree-core/pull/548
